// ---------------------------------------------------------------------------
// Day29 - codec_8b10b_ref_pkg : the golden reference model
//
// The DUT computes 8b/10b from rules: sub-block tables, a disparity rule, an
// alternating-balanced exception, the D.x.A7 exception, and a re-encode step
// in the receiver.  Any one of those rules can be subtly wrong in a way that
// still round-trips, because the same wrong rule sits on both ends of the
// link.  So this model deliberately contains *no rules at all*:
//
//   * encode is a flat 1024-entry ROM, {rd, k, byte} -> {codeword, rd'},
//     generated by docs/gen_kat.py after that script proved the underlying
//     tables against the five defining properties of the code (DC balance,
//     bounded running disparity, run length <= 5 across all ~143k legal
//     codeword junctions, unique decodability, and comma uniqueness);
//
//   * decode is a flat 2048-entry table, {rd, codeword} -> result, built here
//     at elaboration by brute-force inversion of that ROM.  Every one of the
//     1024 possible 10-bit words is classified in both RD states by asking one
//     question - is this exactly the word the transmitter would have sent? -
//     and never by inspecting sub-blocks.
//
// The only thing the two implementations share is the definition of the code
// itself, which is the point.
//
// Classification, in full:
//     word == enc_rom[rd][s] for some symbol s   -> clean decode of s
//     word == enc_rom[~rd][s] for some symbol s  -> disparity error, still s
//     neither                                    -> code error
//
// Running disparity always follows the bits that actually arrived (see
// rd_advance below), so a corrupted symbol costs a transient RD disagreement
// rather than a permanent one - the property the "single bit error, then
// recovery" corner test exists to demonstrate.
// ---------------------------------------------------------------------------

`timescale 1ns/1ps

package codec_8b10b_ref_pkg;

  localparam bit RD_NEG = 1'b0;
  localparam bit RD_POS = 1'b1;

  // ---- encode result -----------------------------------------------------
  // Returned as a struct rather than through output arguments: SystemVerilog
  // functions with non-input ports are not portable across simulators.
  typedef struct packed {
    bit [9:0] code;
    bit       rd_out;
    bit       kerr;
  } ref_tx_t;

  // ---- decode result -----------------------------------------------------
  typedef struct packed {
    bit       code_err;
    bit       disp_err;
    bit       k;
    bit [7:0] data;
    bit       rd_out;
  } ref_rx_t;

  // ---- everything the DUT is expected to produce for one request ---------
  typedef struct packed {
    bit [9:0] enc_code;
    bit [9:0] wire_code;
    bit       enc_kerr;
    bit       enc_comma;
    bit       enc_rd;
    bit [7:0] out_data;
    bit       out_k;
    bit       out_code_err;
    bit       out_disp_err;
    bit       out_comma;
    bit       out_rd;
  } ref_exp_t;

  // Width of ref_exp_t, so a testbench can hold expectations in a plain vector
  // queue (queues of packed structs are not portable).  Assigning a ref_exp_t
  // to and from a vector of this width packs and unpacks it implicitly.
  localparam int REF_EXP_W = 36;

  // ---- the tables --------------------------------------------------------
  bit [10:0] enc_rom [0:1023];   // {rd, k, byte}     -> {code, rd'}
  bit        enc_ok  [0:511];    // {k, byte}         -> symbol exists
  ref_rx_t   dec_tbl [0:2047];   // {rd, code}        -> decode result

  // ---- Known-Answer Table ------------------------------------------------
  int         kat_n = 0;
  string      kat_name [0:63];
  bit [7:0]   kat_data [0:63];
  bit         kat_k    [0:63];
  bit         kat_rd   [0:63];
  bit [9:0]   kat_code [0:63];
  bit         kat_rdo  [0:63];

  function automatic void kat_add(input string name, input bit [7:0] data,
                                  input bit k, input bit rd,
                                  input bit [9:0] code, input bit rd_out);
    kat_name[kat_n] = name;
    kat_data[kat_n] = data;
    kat_k   [kat_n] = k;
    kat_rd  [kat_n] = rd;
    kat_code[kat_n] = code;
    kat_rdo [kat_n] = rd_out;
    kat_n           = kat_n + 1;
  endfunction

  // ---- running disparity implied by a received word ----------------------
  // Stated as a definition rather than borrowed from the DUT: a sub-block with
  // equal ones and zeros leaves RD alone, any other sub-block drives RD to the
  // sign of its own imbalance.  Total, and self-limiting even for words that
  // are not in the code.
  function automatic bit rd_advance(input bit [9:0] cw, input bit rd);
    int n6, n4;
    bit mid;
    n6 = $countones(cw[9:4]);
    n4 = $countones(cw[3:0]);
    mid        = (n6 == 3) ? rd  : ((n6 > 3) ? RD_POS : RD_NEG);
    rd_advance = (n4 == 2) ? mid : ((n4 > 2) ? RD_POS : RD_NEG);
  endfunction

  function automatic bit ref_is_comma(input bit [9:0] cw);
    ref_is_comma = (cw[9:3] == 7'b0011111) || (cw[9:3] == 7'b1100000);
  endfunction

  // ---- build ------------------------------------------------------------
  bit ref_built = 1'b0;

  // Field-by-field rather than an assignment pattern: keeps the package
  // compiling on simulators (Icarus among them) that do not accept named
  // structure literals.
  function automatic ref_rx_t mk_rx(input bit ce, input bit de, input bit k,
                                    input bit [7:0] data, input bit rd_out);
    ref_rx_t r;
    r.code_err = ce;
    r.disp_err = de;
    r.k        = k;
    r.data     = data;
    r.rd_out   = rd_out;
    return r;
  endfunction

  function automatic void ref_build();
    bit [9:0] cw;
    if (ref_built) return;
    ref_built = 1'b1;

    for (int i = 0; i < 1024; i++) enc_rom[i] = '0;
    for (int i = 0; i < 512;  i++) enc_ok [i] = 1'b0;

    // <<<GENERATED-TABLES-BEGIN>>>
    // ---- generated by docs/gen_kat.py; run `make kat` to refresh ----
    // Every legal symbol, fully expanded.  No encode rule is applied
    // anywhere in this package - if the DUT's rules are wrong, these
    // numbers are what say so.

    for (int d = 0; d < 256; d++) enc_ok[{1'b0, d[7:0]}] = 1'b1;
    enc_ok[{1'b1,8'h1C}] = 1'b1; // K.28.0
    enc_ok[{1'b1,8'h3C}] = 1'b1; // K.28.1
    enc_ok[{1'b1,8'h5C}] = 1'b1; // K.28.2
    enc_ok[{1'b1,8'h7C}] = 1'b1; // K.28.3
    enc_ok[{1'b1,8'h9C}] = 1'b1; // K.28.4
    enc_ok[{1'b1,8'hBC}] = 1'b1; // K.28.5
    enc_ok[{1'b1,8'hDC}] = 1'b1; // K.28.6
    enc_ok[{1'b1,8'hFC}] = 1'b1; // K.28.7
    enc_ok[{1'b1,8'hF7}] = 1'b1; // K.23.7
    enc_ok[{1'b1,8'hFB}] = 1'b1; // K.27.7
    enc_ok[{1'b1,8'hFD}] = 1'b1; // K.29.7
    enc_ok[{1'b1,8'hFE}] = 1'b1; // K.30.7

    enc_rom[{1'b0,1'b0,8'h00}] = {10'b1001110100,1'b0}; // D.0.0    rd-
    enc_rom[{1'b1,1'b0,8'h00}] = {10'b0110001011,1'b1}; // D.0.0    rd+
    enc_rom[{1'b0,1'b0,8'h01}] = {10'b0111010100,1'b0}; // D.1.0    rd-
    enc_rom[{1'b1,1'b0,8'h01}] = {10'b1000101011,1'b1}; // D.1.0    rd+
    enc_rom[{1'b0,1'b0,8'h02}] = {10'b1011010100,1'b0}; // D.2.0    rd-
    enc_rom[{1'b1,1'b0,8'h02}] = {10'b0100101011,1'b1}; // D.2.0    rd+
    enc_rom[{1'b0,1'b0,8'h03}] = {10'b1100011011,1'b1}; // D.3.0    rd-
    enc_rom[{1'b1,1'b0,8'h03}] = {10'b1100010100,1'b0}; // D.3.0    rd+
    enc_rom[{1'b0,1'b0,8'h04}] = {10'b1101010100,1'b0}; // D.4.0    rd-
    enc_rom[{1'b1,1'b0,8'h04}] = {10'b0010101011,1'b1}; // D.4.0    rd+
    enc_rom[{1'b0,1'b0,8'h05}] = {10'b1010011011,1'b1}; // D.5.0    rd-
    enc_rom[{1'b1,1'b0,8'h05}] = {10'b1010010100,1'b0}; // D.5.0    rd+
    enc_rom[{1'b0,1'b0,8'h06}] = {10'b0110011011,1'b1}; // D.6.0    rd-
    enc_rom[{1'b1,1'b0,8'h06}] = {10'b0110010100,1'b0}; // D.6.0    rd+
    enc_rom[{1'b0,1'b0,8'h07}] = {10'b1110001011,1'b1}; // D.7.0    rd-
    enc_rom[{1'b1,1'b0,8'h07}] = {10'b0001110100,1'b0}; // D.7.0    rd+
    enc_rom[{1'b0,1'b0,8'h08}] = {10'b1110010100,1'b0}; // D.8.0    rd-
    enc_rom[{1'b1,1'b0,8'h08}] = {10'b0001101011,1'b1}; // D.8.0    rd+
    enc_rom[{1'b0,1'b0,8'h09}] = {10'b1001011011,1'b1}; // D.9.0    rd-
    enc_rom[{1'b1,1'b0,8'h09}] = {10'b1001010100,1'b0}; // D.9.0    rd+
    enc_rom[{1'b0,1'b0,8'h0A}] = {10'b0101011011,1'b1}; // D.10.0   rd-
    enc_rom[{1'b1,1'b0,8'h0A}] = {10'b0101010100,1'b0}; // D.10.0   rd+
    enc_rom[{1'b0,1'b0,8'h0B}] = {10'b1101001011,1'b1}; // D.11.0   rd-
    enc_rom[{1'b1,1'b0,8'h0B}] = {10'b1101000100,1'b0}; // D.11.0   rd+
    enc_rom[{1'b0,1'b0,8'h0C}] = {10'b0011011011,1'b1}; // D.12.0   rd-
    enc_rom[{1'b1,1'b0,8'h0C}] = {10'b0011010100,1'b0}; // D.12.0   rd+
    enc_rom[{1'b0,1'b0,8'h0D}] = {10'b1011001011,1'b1}; // D.13.0   rd-
    enc_rom[{1'b1,1'b0,8'h0D}] = {10'b1011000100,1'b0}; // D.13.0   rd+
    enc_rom[{1'b0,1'b0,8'h0E}] = {10'b0111001011,1'b1}; // D.14.0   rd-
    enc_rom[{1'b1,1'b0,8'h0E}] = {10'b0111000100,1'b0}; // D.14.0   rd+
    enc_rom[{1'b0,1'b0,8'h0F}] = {10'b0101110100,1'b0}; // D.15.0   rd-
    enc_rom[{1'b1,1'b0,8'h0F}] = {10'b1010001011,1'b1}; // D.15.0   rd+
    enc_rom[{1'b0,1'b0,8'h10}] = {10'b0110110100,1'b0}; // D.16.0   rd-
    enc_rom[{1'b1,1'b0,8'h10}] = {10'b1001001011,1'b1}; // D.16.0   rd+
    enc_rom[{1'b0,1'b0,8'h11}] = {10'b1000111011,1'b1}; // D.17.0   rd-
    enc_rom[{1'b1,1'b0,8'h11}] = {10'b1000110100,1'b0}; // D.17.0   rd+
    enc_rom[{1'b0,1'b0,8'h12}] = {10'b0100111011,1'b1}; // D.18.0   rd-
    enc_rom[{1'b1,1'b0,8'h12}] = {10'b0100110100,1'b0}; // D.18.0   rd+
    enc_rom[{1'b0,1'b0,8'h13}] = {10'b1100101011,1'b1}; // D.19.0   rd-
    enc_rom[{1'b1,1'b0,8'h13}] = {10'b1100100100,1'b0}; // D.19.0   rd+
    enc_rom[{1'b0,1'b0,8'h14}] = {10'b0010111011,1'b1}; // D.20.0   rd-
    enc_rom[{1'b1,1'b0,8'h14}] = {10'b0010110100,1'b0}; // D.20.0   rd+
    enc_rom[{1'b0,1'b0,8'h15}] = {10'b1010101011,1'b1}; // D.21.0   rd-
    enc_rom[{1'b1,1'b0,8'h15}] = {10'b1010100100,1'b0}; // D.21.0   rd+
    enc_rom[{1'b0,1'b0,8'h16}] = {10'b0110101011,1'b1}; // D.22.0   rd-
    enc_rom[{1'b1,1'b0,8'h16}] = {10'b0110100100,1'b0}; // D.22.0   rd+
    enc_rom[{1'b0,1'b0,8'h17}] = {10'b1110100100,1'b0}; // D.23.0   rd-
    enc_rom[{1'b1,1'b0,8'h17}] = {10'b0001011011,1'b1}; // D.23.0   rd+
    enc_rom[{1'b0,1'b0,8'h18}] = {10'b1100110100,1'b0}; // D.24.0   rd-
    enc_rom[{1'b1,1'b0,8'h18}] = {10'b0011001011,1'b1}; // D.24.0   rd+
    enc_rom[{1'b0,1'b0,8'h19}] = {10'b1001101011,1'b1}; // D.25.0   rd-
    enc_rom[{1'b1,1'b0,8'h19}] = {10'b1001100100,1'b0}; // D.25.0   rd+
    enc_rom[{1'b0,1'b0,8'h1A}] = {10'b0101101011,1'b1}; // D.26.0   rd-
    enc_rom[{1'b1,1'b0,8'h1A}] = {10'b0101100100,1'b0}; // D.26.0   rd+
    enc_rom[{1'b0,1'b0,8'h1B}] = {10'b1101100100,1'b0}; // D.27.0   rd-
    enc_rom[{1'b1,1'b0,8'h1B}] = {10'b0010011011,1'b1}; // D.27.0   rd+
    enc_rom[{1'b0,1'b0,8'h1C}] = {10'b0011101011,1'b1}; // D.28.0   rd-
    enc_rom[{1'b1,1'b0,8'h1C}] = {10'b0011100100,1'b0}; // D.28.0   rd+
    enc_rom[{1'b0,1'b0,8'h1D}] = {10'b1011100100,1'b0}; // D.29.0   rd-
    enc_rom[{1'b1,1'b0,8'h1D}] = {10'b0100011011,1'b1}; // D.29.0   rd+
    enc_rom[{1'b0,1'b0,8'h1E}] = {10'b0111100100,1'b0}; // D.30.0   rd-
    enc_rom[{1'b1,1'b0,8'h1E}] = {10'b1000011011,1'b1}; // D.30.0   rd+
    enc_rom[{1'b0,1'b0,8'h1F}] = {10'b1010110100,1'b0}; // D.31.0   rd-
    enc_rom[{1'b1,1'b0,8'h1F}] = {10'b0101001011,1'b1}; // D.31.0   rd+
    enc_rom[{1'b0,1'b0,8'h20}] = {10'b1001111001,1'b1}; // D.0.1    rd-
    enc_rom[{1'b1,1'b0,8'h20}] = {10'b0110001001,1'b0}; // D.0.1    rd+
    enc_rom[{1'b0,1'b0,8'h21}] = {10'b0111011001,1'b1}; // D.1.1    rd-
    enc_rom[{1'b1,1'b0,8'h21}] = {10'b1000101001,1'b0}; // D.1.1    rd+
    enc_rom[{1'b0,1'b0,8'h22}] = {10'b1011011001,1'b1}; // D.2.1    rd-
    enc_rom[{1'b1,1'b0,8'h22}] = {10'b0100101001,1'b0}; // D.2.1    rd+
    enc_rom[{1'b0,1'b0,8'h23}] = {10'b1100011001,1'b0}; // D.3.1    rd-
    enc_rom[{1'b1,1'b0,8'h23}] = {10'b1100011001,1'b1}; // D.3.1    rd+
    enc_rom[{1'b0,1'b0,8'h24}] = {10'b1101011001,1'b1}; // D.4.1    rd-
    enc_rom[{1'b1,1'b0,8'h24}] = {10'b0010101001,1'b0}; // D.4.1    rd+
    enc_rom[{1'b0,1'b0,8'h25}] = {10'b1010011001,1'b0}; // D.5.1    rd-
    enc_rom[{1'b1,1'b0,8'h25}] = {10'b1010011001,1'b1}; // D.5.1    rd+
    enc_rom[{1'b0,1'b0,8'h26}] = {10'b0110011001,1'b0}; // D.6.1    rd-
    enc_rom[{1'b1,1'b0,8'h26}] = {10'b0110011001,1'b1}; // D.6.1    rd+
    enc_rom[{1'b0,1'b0,8'h27}] = {10'b1110001001,1'b0}; // D.7.1    rd-
    enc_rom[{1'b1,1'b0,8'h27}] = {10'b0001111001,1'b1}; // D.7.1    rd+
    enc_rom[{1'b0,1'b0,8'h28}] = {10'b1110011001,1'b1}; // D.8.1    rd-
    enc_rom[{1'b1,1'b0,8'h28}] = {10'b0001101001,1'b0}; // D.8.1    rd+
    enc_rom[{1'b0,1'b0,8'h29}] = {10'b1001011001,1'b0}; // D.9.1    rd-
    enc_rom[{1'b1,1'b0,8'h29}] = {10'b1001011001,1'b1}; // D.9.1    rd+
    enc_rom[{1'b0,1'b0,8'h2A}] = {10'b0101011001,1'b0}; // D.10.1   rd-
    enc_rom[{1'b1,1'b0,8'h2A}] = {10'b0101011001,1'b1}; // D.10.1   rd+
    enc_rom[{1'b0,1'b0,8'h2B}] = {10'b1101001001,1'b0}; // D.11.1   rd-
    enc_rom[{1'b1,1'b0,8'h2B}] = {10'b1101001001,1'b1}; // D.11.1   rd+
    enc_rom[{1'b0,1'b0,8'h2C}] = {10'b0011011001,1'b0}; // D.12.1   rd-
    enc_rom[{1'b1,1'b0,8'h2C}] = {10'b0011011001,1'b1}; // D.12.1   rd+
    enc_rom[{1'b0,1'b0,8'h2D}] = {10'b1011001001,1'b0}; // D.13.1   rd-
    enc_rom[{1'b1,1'b0,8'h2D}] = {10'b1011001001,1'b1}; // D.13.1   rd+
    enc_rom[{1'b0,1'b0,8'h2E}] = {10'b0111001001,1'b0}; // D.14.1   rd-
    enc_rom[{1'b1,1'b0,8'h2E}] = {10'b0111001001,1'b1}; // D.14.1   rd+
    enc_rom[{1'b0,1'b0,8'h2F}] = {10'b0101111001,1'b1}; // D.15.1   rd-
    enc_rom[{1'b1,1'b0,8'h2F}] = {10'b1010001001,1'b0}; // D.15.1   rd+
    enc_rom[{1'b0,1'b0,8'h30}] = {10'b0110111001,1'b1}; // D.16.1   rd-
    enc_rom[{1'b1,1'b0,8'h30}] = {10'b1001001001,1'b0}; // D.16.1   rd+
    enc_rom[{1'b0,1'b0,8'h31}] = {10'b1000111001,1'b0}; // D.17.1   rd-
    enc_rom[{1'b1,1'b0,8'h31}] = {10'b1000111001,1'b1}; // D.17.1   rd+
    enc_rom[{1'b0,1'b0,8'h32}] = {10'b0100111001,1'b0}; // D.18.1   rd-
    enc_rom[{1'b1,1'b0,8'h32}] = {10'b0100111001,1'b1}; // D.18.1   rd+
    enc_rom[{1'b0,1'b0,8'h33}] = {10'b1100101001,1'b0}; // D.19.1   rd-
    enc_rom[{1'b1,1'b0,8'h33}] = {10'b1100101001,1'b1}; // D.19.1   rd+
    enc_rom[{1'b0,1'b0,8'h34}] = {10'b0010111001,1'b0}; // D.20.1   rd-
    enc_rom[{1'b1,1'b0,8'h34}] = {10'b0010111001,1'b1}; // D.20.1   rd+
    enc_rom[{1'b0,1'b0,8'h35}] = {10'b1010101001,1'b0}; // D.21.1   rd-
    enc_rom[{1'b1,1'b0,8'h35}] = {10'b1010101001,1'b1}; // D.21.1   rd+
    enc_rom[{1'b0,1'b0,8'h36}] = {10'b0110101001,1'b0}; // D.22.1   rd-
    enc_rom[{1'b1,1'b0,8'h36}] = {10'b0110101001,1'b1}; // D.22.1   rd+
    enc_rom[{1'b0,1'b0,8'h37}] = {10'b1110101001,1'b1}; // D.23.1   rd-
    enc_rom[{1'b1,1'b0,8'h37}] = {10'b0001011001,1'b0}; // D.23.1   rd+
    enc_rom[{1'b0,1'b0,8'h38}] = {10'b1100111001,1'b1}; // D.24.1   rd-
    enc_rom[{1'b1,1'b0,8'h38}] = {10'b0011001001,1'b0}; // D.24.1   rd+
    enc_rom[{1'b0,1'b0,8'h39}] = {10'b1001101001,1'b0}; // D.25.1   rd-
    enc_rom[{1'b1,1'b0,8'h39}] = {10'b1001101001,1'b1}; // D.25.1   rd+
    enc_rom[{1'b0,1'b0,8'h3A}] = {10'b0101101001,1'b0}; // D.26.1   rd-
    enc_rom[{1'b1,1'b0,8'h3A}] = {10'b0101101001,1'b1}; // D.26.1   rd+
    enc_rom[{1'b0,1'b0,8'h3B}] = {10'b1101101001,1'b1}; // D.27.1   rd-
    enc_rom[{1'b1,1'b0,8'h3B}] = {10'b0010011001,1'b0}; // D.27.1   rd+
    enc_rom[{1'b0,1'b0,8'h3C}] = {10'b0011101001,1'b0}; // D.28.1   rd-
    enc_rom[{1'b1,1'b0,8'h3C}] = {10'b0011101001,1'b1}; // D.28.1   rd+
    enc_rom[{1'b0,1'b0,8'h3D}] = {10'b1011101001,1'b1}; // D.29.1   rd-
    enc_rom[{1'b1,1'b0,8'h3D}] = {10'b0100011001,1'b0}; // D.29.1   rd+
    enc_rom[{1'b0,1'b0,8'h3E}] = {10'b0111101001,1'b1}; // D.30.1   rd-
    enc_rom[{1'b1,1'b0,8'h3E}] = {10'b1000011001,1'b0}; // D.30.1   rd+
    enc_rom[{1'b0,1'b0,8'h3F}] = {10'b1010111001,1'b1}; // D.31.1   rd-
    enc_rom[{1'b1,1'b0,8'h3F}] = {10'b0101001001,1'b0}; // D.31.1   rd+
    enc_rom[{1'b0,1'b0,8'h40}] = {10'b1001110101,1'b1}; // D.0.2    rd-
    enc_rom[{1'b1,1'b0,8'h40}] = {10'b0110000101,1'b0}; // D.0.2    rd+
    enc_rom[{1'b0,1'b0,8'h41}] = {10'b0111010101,1'b1}; // D.1.2    rd-
    enc_rom[{1'b1,1'b0,8'h41}] = {10'b1000100101,1'b0}; // D.1.2    rd+
    enc_rom[{1'b0,1'b0,8'h42}] = {10'b1011010101,1'b1}; // D.2.2    rd-
    enc_rom[{1'b1,1'b0,8'h42}] = {10'b0100100101,1'b0}; // D.2.2    rd+
    enc_rom[{1'b0,1'b0,8'h43}] = {10'b1100010101,1'b0}; // D.3.2    rd-
    enc_rom[{1'b1,1'b0,8'h43}] = {10'b1100010101,1'b1}; // D.3.2    rd+
    enc_rom[{1'b0,1'b0,8'h44}] = {10'b1101010101,1'b1}; // D.4.2    rd-
    enc_rom[{1'b1,1'b0,8'h44}] = {10'b0010100101,1'b0}; // D.4.2    rd+
    enc_rom[{1'b0,1'b0,8'h45}] = {10'b1010010101,1'b0}; // D.5.2    rd-
    enc_rom[{1'b1,1'b0,8'h45}] = {10'b1010010101,1'b1}; // D.5.2    rd+
    enc_rom[{1'b0,1'b0,8'h46}] = {10'b0110010101,1'b0}; // D.6.2    rd-
    enc_rom[{1'b1,1'b0,8'h46}] = {10'b0110010101,1'b1}; // D.6.2    rd+
    enc_rom[{1'b0,1'b0,8'h47}] = {10'b1110000101,1'b0}; // D.7.2    rd-
    enc_rom[{1'b1,1'b0,8'h47}] = {10'b0001110101,1'b1}; // D.7.2    rd+
    enc_rom[{1'b0,1'b0,8'h48}] = {10'b1110010101,1'b1}; // D.8.2    rd-
    enc_rom[{1'b1,1'b0,8'h48}] = {10'b0001100101,1'b0}; // D.8.2    rd+
    enc_rom[{1'b0,1'b0,8'h49}] = {10'b1001010101,1'b0}; // D.9.2    rd-
    enc_rom[{1'b1,1'b0,8'h49}] = {10'b1001010101,1'b1}; // D.9.2    rd+
    enc_rom[{1'b0,1'b0,8'h4A}] = {10'b0101010101,1'b0}; // D.10.2   rd-
    enc_rom[{1'b1,1'b0,8'h4A}] = {10'b0101010101,1'b1}; // D.10.2   rd+
    enc_rom[{1'b0,1'b0,8'h4B}] = {10'b1101000101,1'b0}; // D.11.2   rd-
    enc_rom[{1'b1,1'b0,8'h4B}] = {10'b1101000101,1'b1}; // D.11.2   rd+
    enc_rom[{1'b0,1'b0,8'h4C}] = {10'b0011010101,1'b0}; // D.12.2   rd-
    enc_rom[{1'b1,1'b0,8'h4C}] = {10'b0011010101,1'b1}; // D.12.2   rd+
    enc_rom[{1'b0,1'b0,8'h4D}] = {10'b1011000101,1'b0}; // D.13.2   rd-
    enc_rom[{1'b1,1'b0,8'h4D}] = {10'b1011000101,1'b1}; // D.13.2   rd+
    enc_rom[{1'b0,1'b0,8'h4E}] = {10'b0111000101,1'b0}; // D.14.2   rd-
    enc_rom[{1'b1,1'b0,8'h4E}] = {10'b0111000101,1'b1}; // D.14.2   rd+
    enc_rom[{1'b0,1'b0,8'h4F}] = {10'b0101110101,1'b1}; // D.15.2   rd-
    enc_rom[{1'b1,1'b0,8'h4F}] = {10'b1010000101,1'b0}; // D.15.2   rd+
    enc_rom[{1'b0,1'b0,8'h50}] = {10'b0110110101,1'b1}; // D.16.2   rd-
    enc_rom[{1'b1,1'b0,8'h50}] = {10'b1001000101,1'b0}; // D.16.2   rd+
    enc_rom[{1'b0,1'b0,8'h51}] = {10'b1000110101,1'b0}; // D.17.2   rd-
    enc_rom[{1'b1,1'b0,8'h51}] = {10'b1000110101,1'b1}; // D.17.2   rd+
    enc_rom[{1'b0,1'b0,8'h52}] = {10'b0100110101,1'b0}; // D.18.2   rd-
    enc_rom[{1'b1,1'b0,8'h52}] = {10'b0100110101,1'b1}; // D.18.2   rd+
    enc_rom[{1'b0,1'b0,8'h53}] = {10'b1100100101,1'b0}; // D.19.2   rd-
    enc_rom[{1'b1,1'b0,8'h53}] = {10'b1100100101,1'b1}; // D.19.2   rd+
    enc_rom[{1'b0,1'b0,8'h54}] = {10'b0010110101,1'b0}; // D.20.2   rd-
    enc_rom[{1'b1,1'b0,8'h54}] = {10'b0010110101,1'b1}; // D.20.2   rd+
    enc_rom[{1'b0,1'b0,8'h55}] = {10'b1010100101,1'b0}; // D.21.2   rd-
    enc_rom[{1'b1,1'b0,8'h55}] = {10'b1010100101,1'b1}; // D.21.2   rd+
    enc_rom[{1'b0,1'b0,8'h56}] = {10'b0110100101,1'b0}; // D.22.2   rd-
    enc_rom[{1'b1,1'b0,8'h56}] = {10'b0110100101,1'b1}; // D.22.2   rd+
    enc_rom[{1'b0,1'b0,8'h57}] = {10'b1110100101,1'b1}; // D.23.2   rd-
    enc_rom[{1'b1,1'b0,8'h57}] = {10'b0001010101,1'b0}; // D.23.2   rd+
    enc_rom[{1'b0,1'b0,8'h58}] = {10'b1100110101,1'b1}; // D.24.2   rd-
    enc_rom[{1'b1,1'b0,8'h58}] = {10'b0011000101,1'b0}; // D.24.2   rd+
    enc_rom[{1'b0,1'b0,8'h59}] = {10'b1001100101,1'b0}; // D.25.2   rd-
    enc_rom[{1'b1,1'b0,8'h59}] = {10'b1001100101,1'b1}; // D.25.2   rd+
    enc_rom[{1'b0,1'b0,8'h5A}] = {10'b0101100101,1'b0}; // D.26.2   rd-
    enc_rom[{1'b1,1'b0,8'h5A}] = {10'b0101100101,1'b1}; // D.26.2   rd+
    enc_rom[{1'b0,1'b0,8'h5B}] = {10'b1101100101,1'b1}; // D.27.2   rd-
    enc_rom[{1'b1,1'b0,8'h5B}] = {10'b0010010101,1'b0}; // D.27.2   rd+
    enc_rom[{1'b0,1'b0,8'h5C}] = {10'b0011100101,1'b0}; // D.28.2   rd-
    enc_rom[{1'b1,1'b0,8'h5C}] = {10'b0011100101,1'b1}; // D.28.2   rd+
    enc_rom[{1'b0,1'b0,8'h5D}] = {10'b1011100101,1'b1}; // D.29.2   rd-
    enc_rom[{1'b1,1'b0,8'h5D}] = {10'b0100010101,1'b0}; // D.29.2   rd+
    enc_rom[{1'b0,1'b0,8'h5E}] = {10'b0111100101,1'b1}; // D.30.2   rd-
    enc_rom[{1'b1,1'b0,8'h5E}] = {10'b1000010101,1'b0}; // D.30.2   rd+
    enc_rom[{1'b0,1'b0,8'h5F}] = {10'b1010110101,1'b1}; // D.31.2   rd-
    enc_rom[{1'b1,1'b0,8'h5F}] = {10'b0101000101,1'b0}; // D.31.2   rd+
    enc_rom[{1'b0,1'b0,8'h60}] = {10'b1001110011,1'b1}; // D.0.3    rd-
    enc_rom[{1'b1,1'b0,8'h60}] = {10'b0110001100,1'b0}; // D.0.3    rd+
    enc_rom[{1'b0,1'b0,8'h61}] = {10'b0111010011,1'b1}; // D.1.3    rd-
    enc_rom[{1'b1,1'b0,8'h61}] = {10'b1000101100,1'b0}; // D.1.3    rd+
    enc_rom[{1'b0,1'b0,8'h62}] = {10'b1011010011,1'b1}; // D.2.3    rd-
    enc_rom[{1'b1,1'b0,8'h62}] = {10'b0100101100,1'b0}; // D.2.3    rd+
    enc_rom[{1'b0,1'b0,8'h63}] = {10'b1100011100,1'b0}; // D.3.3    rd-
    enc_rom[{1'b1,1'b0,8'h63}] = {10'b1100010011,1'b1}; // D.3.3    rd+
    enc_rom[{1'b0,1'b0,8'h64}] = {10'b1101010011,1'b1}; // D.4.3    rd-
    enc_rom[{1'b1,1'b0,8'h64}] = {10'b0010101100,1'b0}; // D.4.3    rd+
    enc_rom[{1'b0,1'b0,8'h65}] = {10'b1010011100,1'b0}; // D.5.3    rd-
    enc_rom[{1'b1,1'b0,8'h65}] = {10'b1010010011,1'b1}; // D.5.3    rd+
    enc_rom[{1'b0,1'b0,8'h66}] = {10'b0110011100,1'b0}; // D.6.3    rd-
    enc_rom[{1'b1,1'b0,8'h66}] = {10'b0110010011,1'b1}; // D.6.3    rd+
    enc_rom[{1'b0,1'b0,8'h67}] = {10'b1110001100,1'b0}; // D.7.3    rd-
    enc_rom[{1'b1,1'b0,8'h67}] = {10'b0001110011,1'b1}; // D.7.3    rd+
    enc_rom[{1'b0,1'b0,8'h68}] = {10'b1110010011,1'b1}; // D.8.3    rd-
    enc_rom[{1'b1,1'b0,8'h68}] = {10'b0001101100,1'b0}; // D.8.3    rd+
    enc_rom[{1'b0,1'b0,8'h69}] = {10'b1001011100,1'b0}; // D.9.3    rd-
    enc_rom[{1'b1,1'b0,8'h69}] = {10'b1001010011,1'b1}; // D.9.3    rd+
    enc_rom[{1'b0,1'b0,8'h6A}] = {10'b0101011100,1'b0}; // D.10.3   rd-
    enc_rom[{1'b1,1'b0,8'h6A}] = {10'b0101010011,1'b1}; // D.10.3   rd+
    enc_rom[{1'b0,1'b0,8'h6B}] = {10'b1101001100,1'b0}; // D.11.3   rd-
    enc_rom[{1'b1,1'b0,8'h6B}] = {10'b1101000011,1'b1}; // D.11.3   rd+
    enc_rom[{1'b0,1'b0,8'h6C}] = {10'b0011011100,1'b0}; // D.12.3   rd-
    enc_rom[{1'b1,1'b0,8'h6C}] = {10'b0011010011,1'b1}; // D.12.3   rd+
    enc_rom[{1'b0,1'b0,8'h6D}] = {10'b1011001100,1'b0}; // D.13.3   rd-
    enc_rom[{1'b1,1'b0,8'h6D}] = {10'b1011000011,1'b1}; // D.13.3   rd+
    enc_rom[{1'b0,1'b0,8'h6E}] = {10'b0111001100,1'b0}; // D.14.3   rd-
    enc_rom[{1'b1,1'b0,8'h6E}] = {10'b0111000011,1'b1}; // D.14.3   rd+
    enc_rom[{1'b0,1'b0,8'h6F}] = {10'b0101110011,1'b1}; // D.15.3   rd-
    enc_rom[{1'b1,1'b0,8'h6F}] = {10'b1010001100,1'b0}; // D.15.3   rd+
    enc_rom[{1'b0,1'b0,8'h70}] = {10'b0110110011,1'b1}; // D.16.3   rd-
    enc_rom[{1'b1,1'b0,8'h70}] = {10'b1001001100,1'b0}; // D.16.3   rd+
    enc_rom[{1'b0,1'b0,8'h71}] = {10'b1000111100,1'b0}; // D.17.3   rd-
    enc_rom[{1'b1,1'b0,8'h71}] = {10'b1000110011,1'b1}; // D.17.3   rd+
    enc_rom[{1'b0,1'b0,8'h72}] = {10'b0100111100,1'b0}; // D.18.3   rd-
    enc_rom[{1'b1,1'b0,8'h72}] = {10'b0100110011,1'b1}; // D.18.3   rd+
    enc_rom[{1'b0,1'b0,8'h73}] = {10'b1100101100,1'b0}; // D.19.3   rd-
    enc_rom[{1'b1,1'b0,8'h73}] = {10'b1100100011,1'b1}; // D.19.3   rd+
    enc_rom[{1'b0,1'b0,8'h74}] = {10'b0010111100,1'b0}; // D.20.3   rd-
    enc_rom[{1'b1,1'b0,8'h74}] = {10'b0010110011,1'b1}; // D.20.3   rd+
    enc_rom[{1'b0,1'b0,8'h75}] = {10'b1010101100,1'b0}; // D.21.3   rd-
    enc_rom[{1'b1,1'b0,8'h75}] = {10'b1010100011,1'b1}; // D.21.3   rd+
    enc_rom[{1'b0,1'b0,8'h76}] = {10'b0110101100,1'b0}; // D.22.3   rd-
    enc_rom[{1'b1,1'b0,8'h76}] = {10'b0110100011,1'b1}; // D.22.3   rd+
    enc_rom[{1'b0,1'b0,8'h77}] = {10'b1110100011,1'b1}; // D.23.3   rd-
    enc_rom[{1'b1,1'b0,8'h77}] = {10'b0001011100,1'b0}; // D.23.3   rd+
    enc_rom[{1'b0,1'b0,8'h78}] = {10'b1100110011,1'b1}; // D.24.3   rd-
    enc_rom[{1'b1,1'b0,8'h78}] = {10'b0011001100,1'b0}; // D.24.3   rd+
    enc_rom[{1'b0,1'b0,8'h79}] = {10'b1001101100,1'b0}; // D.25.3   rd-
    enc_rom[{1'b1,1'b0,8'h79}] = {10'b1001100011,1'b1}; // D.25.3   rd+
    enc_rom[{1'b0,1'b0,8'h7A}] = {10'b0101101100,1'b0}; // D.26.3   rd-
    enc_rom[{1'b1,1'b0,8'h7A}] = {10'b0101100011,1'b1}; // D.26.3   rd+
    enc_rom[{1'b0,1'b0,8'h7B}] = {10'b1101100011,1'b1}; // D.27.3   rd-
    enc_rom[{1'b1,1'b0,8'h7B}] = {10'b0010011100,1'b0}; // D.27.3   rd+
    enc_rom[{1'b0,1'b0,8'h7C}] = {10'b0011101100,1'b0}; // D.28.3   rd-
    enc_rom[{1'b1,1'b0,8'h7C}] = {10'b0011100011,1'b1}; // D.28.3   rd+
    enc_rom[{1'b0,1'b0,8'h7D}] = {10'b1011100011,1'b1}; // D.29.3   rd-
    enc_rom[{1'b1,1'b0,8'h7D}] = {10'b0100011100,1'b0}; // D.29.3   rd+
    enc_rom[{1'b0,1'b0,8'h7E}] = {10'b0111100011,1'b1}; // D.30.3   rd-
    enc_rom[{1'b1,1'b0,8'h7E}] = {10'b1000011100,1'b0}; // D.30.3   rd+
    enc_rom[{1'b0,1'b0,8'h7F}] = {10'b1010110011,1'b1}; // D.31.3   rd-
    enc_rom[{1'b1,1'b0,8'h7F}] = {10'b0101001100,1'b0}; // D.31.3   rd+
    enc_rom[{1'b0,1'b0,8'h80}] = {10'b1001110010,1'b0}; // D.0.4    rd-
    enc_rom[{1'b1,1'b0,8'h80}] = {10'b0110001101,1'b1}; // D.0.4    rd+
    enc_rom[{1'b0,1'b0,8'h81}] = {10'b0111010010,1'b0}; // D.1.4    rd-
    enc_rom[{1'b1,1'b0,8'h81}] = {10'b1000101101,1'b1}; // D.1.4    rd+
    enc_rom[{1'b0,1'b0,8'h82}] = {10'b1011010010,1'b0}; // D.2.4    rd-
    enc_rom[{1'b1,1'b0,8'h82}] = {10'b0100101101,1'b1}; // D.2.4    rd+
    enc_rom[{1'b0,1'b0,8'h83}] = {10'b1100011101,1'b1}; // D.3.4    rd-
    enc_rom[{1'b1,1'b0,8'h83}] = {10'b1100010010,1'b0}; // D.3.4    rd+
    enc_rom[{1'b0,1'b0,8'h84}] = {10'b1101010010,1'b0}; // D.4.4    rd-
    enc_rom[{1'b1,1'b0,8'h84}] = {10'b0010101101,1'b1}; // D.4.4    rd+
    enc_rom[{1'b0,1'b0,8'h85}] = {10'b1010011101,1'b1}; // D.5.4    rd-
    enc_rom[{1'b1,1'b0,8'h85}] = {10'b1010010010,1'b0}; // D.5.4    rd+
    enc_rom[{1'b0,1'b0,8'h86}] = {10'b0110011101,1'b1}; // D.6.4    rd-
    enc_rom[{1'b1,1'b0,8'h86}] = {10'b0110010010,1'b0}; // D.6.4    rd+
    enc_rom[{1'b0,1'b0,8'h87}] = {10'b1110001101,1'b1}; // D.7.4    rd-
    enc_rom[{1'b1,1'b0,8'h87}] = {10'b0001110010,1'b0}; // D.7.4    rd+
    enc_rom[{1'b0,1'b0,8'h88}] = {10'b1110010010,1'b0}; // D.8.4    rd-
    enc_rom[{1'b1,1'b0,8'h88}] = {10'b0001101101,1'b1}; // D.8.4    rd+
    enc_rom[{1'b0,1'b0,8'h89}] = {10'b1001011101,1'b1}; // D.9.4    rd-
    enc_rom[{1'b1,1'b0,8'h89}] = {10'b1001010010,1'b0}; // D.9.4    rd+
    enc_rom[{1'b0,1'b0,8'h8A}] = {10'b0101011101,1'b1}; // D.10.4   rd-
    enc_rom[{1'b1,1'b0,8'h8A}] = {10'b0101010010,1'b0}; // D.10.4   rd+
    enc_rom[{1'b0,1'b0,8'h8B}] = {10'b1101001101,1'b1}; // D.11.4   rd-
    enc_rom[{1'b1,1'b0,8'h8B}] = {10'b1101000010,1'b0}; // D.11.4   rd+
    enc_rom[{1'b0,1'b0,8'h8C}] = {10'b0011011101,1'b1}; // D.12.4   rd-
    enc_rom[{1'b1,1'b0,8'h8C}] = {10'b0011010010,1'b0}; // D.12.4   rd+
    enc_rom[{1'b0,1'b0,8'h8D}] = {10'b1011001101,1'b1}; // D.13.4   rd-
    enc_rom[{1'b1,1'b0,8'h8D}] = {10'b1011000010,1'b0}; // D.13.4   rd+
    enc_rom[{1'b0,1'b0,8'h8E}] = {10'b0111001101,1'b1}; // D.14.4   rd-
    enc_rom[{1'b1,1'b0,8'h8E}] = {10'b0111000010,1'b0}; // D.14.4   rd+
    enc_rom[{1'b0,1'b0,8'h8F}] = {10'b0101110010,1'b0}; // D.15.4   rd-
    enc_rom[{1'b1,1'b0,8'h8F}] = {10'b1010001101,1'b1}; // D.15.4   rd+
    enc_rom[{1'b0,1'b0,8'h90}] = {10'b0110110010,1'b0}; // D.16.4   rd-
    enc_rom[{1'b1,1'b0,8'h90}] = {10'b1001001101,1'b1}; // D.16.4   rd+
    enc_rom[{1'b0,1'b0,8'h91}] = {10'b1000111101,1'b1}; // D.17.4   rd-
    enc_rom[{1'b1,1'b0,8'h91}] = {10'b1000110010,1'b0}; // D.17.4   rd+
    enc_rom[{1'b0,1'b0,8'h92}] = {10'b0100111101,1'b1}; // D.18.4   rd-
    enc_rom[{1'b1,1'b0,8'h92}] = {10'b0100110010,1'b0}; // D.18.4   rd+
    enc_rom[{1'b0,1'b0,8'h93}] = {10'b1100101101,1'b1}; // D.19.4   rd-
    enc_rom[{1'b1,1'b0,8'h93}] = {10'b1100100010,1'b0}; // D.19.4   rd+
    enc_rom[{1'b0,1'b0,8'h94}] = {10'b0010111101,1'b1}; // D.20.4   rd-
    enc_rom[{1'b1,1'b0,8'h94}] = {10'b0010110010,1'b0}; // D.20.4   rd+
    enc_rom[{1'b0,1'b0,8'h95}] = {10'b1010101101,1'b1}; // D.21.4   rd-
    enc_rom[{1'b1,1'b0,8'h95}] = {10'b1010100010,1'b0}; // D.21.4   rd+
    enc_rom[{1'b0,1'b0,8'h96}] = {10'b0110101101,1'b1}; // D.22.4   rd-
    enc_rom[{1'b1,1'b0,8'h96}] = {10'b0110100010,1'b0}; // D.22.4   rd+
    enc_rom[{1'b0,1'b0,8'h97}] = {10'b1110100010,1'b0}; // D.23.4   rd-
    enc_rom[{1'b1,1'b0,8'h97}] = {10'b0001011101,1'b1}; // D.23.4   rd+
    enc_rom[{1'b0,1'b0,8'h98}] = {10'b1100110010,1'b0}; // D.24.4   rd-
    enc_rom[{1'b1,1'b0,8'h98}] = {10'b0011001101,1'b1}; // D.24.4   rd+
    enc_rom[{1'b0,1'b0,8'h99}] = {10'b1001101101,1'b1}; // D.25.4   rd-
    enc_rom[{1'b1,1'b0,8'h99}] = {10'b1001100010,1'b0}; // D.25.4   rd+
    enc_rom[{1'b0,1'b0,8'h9A}] = {10'b0101101101,1'b1}; // D.26.4   rd-
    enc_rom[{1'b1,1'b0,8'h9A}] = {10'b0101100010,1'b0}; // D.26.4   rd+
    enc_rom[{1'b0,1'b0,8'h9B}] = {10'b1101100010,1'b0}; // D.27.4   rd-
    enc_rom[{1'b1,1'b0,8'h9B}] = {10'b0010011101,1'b1}; // D.27.4   rd+
    enc_rom[{1'b0,1'b0,8'h9C}] = {10'b0011101101,1'b1}; // D.28.4   rd-
    enc_rom[{1'b1,1'b0,8'h9C}] = {10'b0011100010,1'b0}; // D.28.4   rd+
    enc_rom[{1'b0,1'b0,8'h9D}] = {10'b1011100010,1'b0}; // D.29.4   rd-
    enc_rom[{1'b1,1'b0,8'h9D}] = {10'b0100011101,1'b1}; // D.29.4   rd+
    enc_rom[{1'b0,1'b0,8'h9E}] = {10'b0111100010,1'b0}; // D.30.4   rd-
    enc_rom[{1'b1,1'b0,8'h9E}] = {10'b1000011101,1'b1}; // D.30.4   rd+
    enc_rom[{1'b0,1'b0,8'h9F}] = {10'b1010110010,1'b0}; // D.31.4   rd-
    enc_rom[{1'b1,1'b0,8'h9F}] = {10'b0101001101,1'b1}; // D.31.4   rd+
    enc_rom[{1'b0,1'b0,8'hA0}] = {10'b1001111010,1'b1}; // D.0.5    rd-
    enc_rom[{1'b1,1'b0,8'hA0}] = {10'b0110001010,1'b0}; // D.0.5    rd+
    enc_rom[{1'b0,1'b0,8'hA1}] = {10'b0111011010,1'b1}; // D.1.5    rd-
    enc_rom[{1'b1,1'b0,8'hA1}] = {10'b1000101010,1'b0}; // D.1.5    rd+
    enc_rom[{1'b0,1'b0,8'hA2}] = {10'b1011011010,1'b1}; // D.2.5    rd-
    enc_rom[{1'b1,1'b0,8'hA2}] = {10'b0100101010,1'b0}; // D.2.5    rd+
    enc_rom[{1'b0,1'b0,8'hA3}] = {10'b1100011010,1'b0}; // D.3.5    rd-
    enc_rom[{1'b1,1'b0,8'hA3}] = {10'b1100011010,1'b1}; // D.3.5    rd+
    enc_rom[{1'b0,1'b0,8'hA4}] = {10'b1101011010,1'b1}; // D.4.5    rd-
    enc_rom[{1'b1,1'b0,8'hA4}] = {10'b0010101010,1'b0}; // D.4.5    rd+
    enc_rom[{1'b0,1'b0,8'hA5}] = {10'b1010011010,1'b0}; // D.5.5    rd-
    enc_rom[{1'b1,1'b0,8'hA5}] = {10'b1010011010,1'b1}; // D.5.5    rd+
    enc_rom[{1'b0,1'b0,8'hA6}] = {10'b0110011010,1'b0}; // D.6.5    rd-
    enc_rom[{1'b1,1'b0,8'hA6}] = {10'b0110011010,1'b1}; // D.6.5    rd+
    enc_rom[{1'b0,1'b0,8'hA7}] = {10'b1110001010,1'b0}; // D.7.5    rd-
    enc_rom[{1'b1,1'b0,8'hA7}] = {10'b0001111010,1'b1}; // D.7.5    rd+
    enc_rom[{1'b0,1'b0,8'hA8}] = {10'b1110011010,1'b1}; // D.8.5    rd-
    enc_rom[{1'b1,1'b0,8'hA8}] = {10'b0001101010,1'b0}; // D.8.5    rd+
    enc_rom[{1'b0,1'b0,8'hA9}] = {10'b1001011010,1'b0}; // D.9.5    rd-
    enc_rom[{1'b1,1'b0,8'hA9}] = {10'b1001011010,1'b1}; // D.9.5    rd+
    enc_rom[{1'b0,1'b0,8'hAA}] = {10'b0101011010,1'b0}; // D.10.5   rd-
    enc_rom[{1'b1,1'b0,8'hAA}] = {10'b0101011010,1'b1}; // D.10.5   rd+
    enc_rom[{1'b0,1'b0,8'hAB}] = {10'b1101001010,1'b0}; // D.11.5   rd-
    enc_rom[{1'b1,1'b0,8'hAB}] = {10'b1101001010,1'b1}; // D.11.5   rd+
    enc_rom[{1'b0,1'b0,8'hAC}] = {10'b0011011010,1'b0}; // D.12.5   rd-
    enc_rom[{1'b1,1'b0,8'hAC}] = {10'b0011011010,1'b1}; // D.12.5   rd+
    enc_rom[{1'b0,1'b0,8'hAD}] = {10'b1011001010,1'b0}; // D.13.5   rd-
    enc_rom[{1'b1,1'b0,8'hAD}] = {10'b1011001010,1'b1}; // D.13.5   rd+
    enc_rom[{1'b0,1'b0,8'hAE}] = {10'b0111001010,1'b0}; // D.14.5   rd-
    enc_rom[{1'b1,1'b0,8'hAE}] = {10'b0111001010,1'b1}; // D.14.5   rd+
    enc_rom[{1'b0,1'b0,8'hAF}] = {10'b0101111010,1'b1}; // D.15.5   rd-
    enc_rom[{1'b1,1'b0,8'hAF}] = {10'b1010001010,1'b0}; // D.15.5   rd+
    enc_rom[{1'b0,1'b0,8'hB0}] = {10'b0110111010,1'b1}; // D.16.5   rd-
    enc_rom[{1'b1,1'b0,8'hB0}] = {10'b1001001010,1'b0}; // D.16.5   rd+
    enc_rom[{1'b0,1'b0,8'hB1}] = {10'b1000111010,1'b0}; // D.17.5   rd-
    enc_rom[{1'b1,1'b0,8'hB1}] = {10'b1000111010,1'b1}; // D.17.5   rd+
    enc_rom[{1'b0,1'b0,8'hB2}] = {10'b0100111010,1'b0}; // D.18.5   rd-
    enc_rom[{1'b1,1'b0,8'hB2}] = {10'b0100111010,1'b1}; // D.18.5   rd+
    enc_rom[{1'b0,1'b0,8'hB3}] = {10'b1100101010,1'b0}; // D.19.5   rd-
    enc_rom[{1'b1,1'b0,8'hB3}] = {10'b1100101010,1'b1}; // D.19.5   rd+
    enc_rom[{1'b0,1'b0,8'hB4}] = {10'b0010111010,1'b0}; // D.20.5   rd-
    enc_rom[{1'b1,1'b0,8'hB4}] = {10'b0010111010,1'b1}; // D.20.5   rd+
    enc_rom[{1'b0,1'b0,8'hB5}] = {10'b1010101010,1'b0}; // D.21.5   rd-
    enc_rom[{1'b1,1'b0,8'hB5}] = {10'b1010101010,1'b1}; // D.21.5   rd+
    enc_rom[{1'b0,1'b0,8'hB6}] = {10'b0110101010,1'b0}; // D.22.5   rd-
    enc_rom[{1'b1,1'b0,8'hB6}] = {10'b0110101010,1'b1}; // D.22.5   rd+
    enc_rom[{1'b0,1'b0,8'hB7}] = {10'b1110101010,1'b1}; // D.23.5   rd-
    enc_rom[{1'b1,1'b0,8'hB7}] = {10'b0001011010,1'b0}; // D.23.5   rd+
    enc_rom[{1'b0,1'b0,8'hB8}] = {10'b1100111010,1'b1}; // D.24.5   rd-
    enc_rom[{1'b1,1'b0,8'hB8}] = {10'b0011001010,1'b0}; // D.24.5   rd+
    enc_rom[{1'b0,1'b0,8'hB9}] = {10'b1001101010,1'b0}; // D.25.5   rd-
    enc_rom[{1'b1,1'b0,8'hB9}] = {10'b1001101010,1'b1}; // D.25.5   rd+
    enc_rom[{1'b0,1'b0,8'hBA}] = {10'b0101101010,1'b0}; // D.26.5   rd-
    enc_rom[{1'b1,1'b0,8'hBA}] = {10'b0101101010,1'b1}; // D.26.5   rd+
    enc_rom[{1'b0,1'b0,8'hBB}] = {10'b1101101010,1'b1}; // D.27.5   rd-
    enc_rom[{1'b1,1'b0,8'hBB}] = {10'b0010011010,1'b0}; // D.27.5   rd+
    enc_rom[{1'b0,1'b0,8'hBC}] = {10'b0011101010,1'b0}; // D.28.5   rd-
    enc_rom[{1'b1,1'b0,8'hBC}] = {10'b0011101010,1'b1}; // D.28.5   rd+
    enc_rom[{1'b0,1'b0,8'hBD}] = {10'b1011101010,1'b1}; // D.29.5   rd-
    enc_rom[{1'b1,1'b0,8'hBD}] = {10'b0100011010,1'b0}; // D.29.5   rd+
    enc_rom[{1'b0,1'b0,8'hBE}] = {10'b0111101010,1'b1}; // D.30.5   rd-
    enc_rom[{1'b1,1'b0,8'hBE}] = {10'b1000011010,1'b0}; // D.30.5   rd+
    enc_rom[{1'b0,1'b0,8'hBF}] = {10'b1010111010,1'b1}; // D.31.5   rd-
    enc_rom[{1'b1,1'b0,8'hBF}] = {10'b0101001010,1'b0}; // D.31.5   rd+
    enc_rom[{1'b0,1'b0,8'hC0}] = {10'b1001110110,1'b1}; // D.0.6    rd-
    enc_rom[{1'b1,1'b0,8'hC0}] = {10'b0110000110,1'b0}; // D.0.6    rd+
    enc_rom[{1'b0,1'b0,8'hC1}] = {10'b0111010110,1'b1}; // D.1.6    rd-
    enc_rom[{1'b1,1'b0,8'hC1}] = {10'b1000100110,1'b0}; // D.1.6    rd+
    enc_rom[{1'b0,1'b0,8'hC2}] = {10'b1011010110,1'b1}; // D.2.6    rd-
    enc_rom[{1'b1,1'b0,8'hC2}] = {10'b0100100110,1'b0}; // D.2.6    rd+
    enc_rom[{1'b0,1'b0,8'hC3}] = {10'b1100010110,1'b0}; // D.3.6    rd-
    enc_rom[{1'b1,1'b0,8'hC3}] = {10'b1100010110,1'b1}; // D.3.6    rd+
    enc_rom[{1'b0,1'b0,8'hC4}] = {10'b1101010110,1'b1}; // D.4.6    rd-
    enc_rom[{1'b1,1'b0,8'hC4}] = {10'b0010100110,1'b0}; // D.4.6    rd+
    enc_rom[{1'b0,1'b0,8'hC5}] = {10'b1010010110,1'b0}; // D.5.6    rd-
    enc_rom[{1'b1,1'b0,8'hC5}] = {10'b1010010110,1'b1}; // D.5.6    rd+
    enc_rom[{1'b0,1'b0,8'hC6}] = {10'b0110010110,1'b0}; // D.6.6    rd-
    enc_rom[{1'b1,1'b0,8'hC6}] = {10'b0110010110,1'b1}; // D.6.6    rd+
    enc_rom[{1'b0,1'b0,8'hC7}] = {10'b1110000110,1'b0}; // D.7.6    rd-
    enc_rom[{1'b1,1'b0,8'hC7}] = {10'b0001110110,1'b1}; // D.7.6    rd+
    enc_rom[{1'b0,1'b0,8'hC8}] = {10'b1110010110,1'b1}; // D.8.6    rd-
    enc_rom[{1'b1,1'b0,8'hC8}] = {10'b0001100110,1'b0}; // D.8.6    rd+
    enc_rom[{1'b0,1'b0,8'hC9}] = {10'b1001010110,1'b0}; // D.9.6    rd-
    enc_rom[{1'b1,1'b0,8'hC9}] = {10'b1001010110,1'b1}; // D.9.6    rd+
    enc_rom[{1'b0,1'b0,8'hCA}] = {10'b0101010110,1'b0}; // D.10.6   rd-
    enc_rom[{1'b1,1'b0,8'hCA}] = {10'b0101010110,1'b1}; // D.10.6   rd+
    enc_rom[{1'b0,1'b0,8'hCB}] = {10'b1101000110,1'b0}; // D.11.6   rd-
    enc_rom[{1'b1,1'b0,8'hCB}] = {10'b1101000110,1'b1}; // D.11.6   rd+
    enc_rom[{1'b0,1'b0,8'hCC}] = {10'b0011010110,1'b0}; // D.12.6   rd-
    enc_rom[{1'b1,1'b0,8'hCC}] = {10'b0011010110,1'b1}; // D.12.6   rd+
    enc_rom[{1'b0,1'b0,8'hCD}] = {10'b1011000110,1'b0}; // D.13.6   rd-
    enc_rom[{1'b1,1'b0,8'hCD}] = {10'b1011000110,1'b1}; // D.13.6   rd+
    enc_rom[{1'b0,1'b0,8'hCE}] = {10'b0111000110,1'b0}; // D.14.6   rd-
    enc_rom[{1'b1,1'b0,8'hCE}] = {10'b0111000110,1'b1}; // D.14.6   rd+
    enc_rom[{1'b0,1'b0,8'hCF}] = {10'b0101110110,1'b1}; // D.15.6   rd-
    enc_rom[{1'b1,1'b0,8'hCF}] = {10'b1010000110,1'b0}; // D.15.6   rd+
    enc_rom[{1'b0,1'b0,8'hD0}] = {10'b0110110110,1'b1}; // D.16.6   rd-
    enc_rom[{1'b1,1'b0,8'hD0}] = {10'b1001000110,1'b0}; // D.16.6   rd+
    enc_rom[{1'b0,1'b0,8'hD1}] = {10'b1000110110,1'b0}; // D.17.6   rd-
    enc_rom[{1'b1,1'b0,8'hD1}] = {10'b1000110110,1'b1}; // D.17.6   rd+
    enc_rom[{1'b0,1'b0,8'hD2}] = {10'b0100110110,1'b0}; // D.18.6   rd-
    enc_rom[{1'b1,1'b0,8'hD2}] = {10'b0100110110,1'b1}; // D.18.6   rd+
    enc_rom[{1'b0,1'b0,8'hD3}] = {10'b1100100110,1'b0}; // D.19.6   rd-
    enc_rom[{1'b1,1'b0,8'hD3}] = {10'b1100100110,1'b1}; // D.19.6   rd+
    enc_rom[{1'b0,1'b0,8'hD4}] = {10'b0010110110,1'b0}; // D.20.6   rd-
    enc_rom[{1'b1,1'b0,8'hD4}] = {10'b0010110110,1'b1}; // D.20.6   rd+
    enc_rom[{1'b0,1'b0,8'hD5}] = {10'b1010100110,1'b0}; // D.21.6   rd-
    enc_rom[{1'b1,1'b0,8'hD5}] = {10'b1010100110,1'b1}; // D.21.6   rd+
    enc_rom[{1'b0,1'b0,8'hD6}] = {10'b0110100110,1'b0}; // D.22.6   rd-
    enc_rom[{1'b1,1'b0,8'hD6}] = {10'b0110100110,1'b1}; // D.22.6   rd+
    enc_rom[{1'b0,1'b0,8'hD7}] = {10'b1110100110,1'b1}; // D.23.6   rd-
    enc_rom[{1'b1,1'b0,8'hD7}] = {10'b0001010110,1'b0}; // D.23.6   rd+
    enc_rom[{1'b0,1'b0,8'hD8}] = {10'b1100110110,1'b1}; // D.24.6   rd-
    enc_rom[{1'b1,1'b0,8'hD8}] = {10'b0011000110,1'b0}; // D.24.6   rd+
    enc_rom[{1'b0,1'b0,8'hD9}] = {10'b1001100110,1'b0}; // D.25.6   rd-
    enc_rom[{1'b1,1'b0,8'hD9}] = {10'b1001100110,1'b1}; // D.25.6   rd+
    enc_rom[{1'b0,1'b0,8'hDA}] = {10'b0101100110,1'b0}; // D.26.6   rd-
    enc_rom[{1'b1,1'b0,8'hDA}] = {10'b0101100110,1'b1}; // D.26.6   rd+
    enc_rom[{1'b0,1'b0,8'hDB}] = {10'b1101100110,1'b1}; // D.27.6   rd-
    enc_rom[{1'b1,1'b0,8'hDB}] = {10'b0010010110,1'b0}; // D.27.6   rd+
    enc_rom[{1'b0,1'b0,8'hDC}] = {10'b0011100110,1'b0}; // D.28.6   rd-
    enc_rom[{1'b1,1'b0,8'hDC}] = {10'b0011100110,1'b1}; // D.28.6   rd+
    enc_rom[{1'b0,1'b0,8'hDD}] = {10'b1011100110,1'b1}; // D.29.6   rd-
    enc_rom[{1'b1,1'b0,8'hDD}] = {10'b0100010110,1'b0}; // D.29.6   rd+
    enc_rom[{1'b0,1'b0,8'hDE}] = {10'b0111100110,1'b1}; // D.30.6   rd-
    enc_rom[{1'b1,1'b0,8'hDE}] = {10'b1000010110,1'b0}; // D.30.6   rd+
    enc_rom[{1'b0,1'b0,8'hDF}] = {10'b1010110110,1'b1}; // D.31.6   rd-
    enc_rom[{1'b1,1'b0,8'hDF}] = {10'b0101000110,1'b0}; // D.31.6   rd+
    enc_rom[{1'b0,1'b0,8'hE0}] = {10'b1001110001,1'b0}; // D.0.7    rd-
    enc_rom[{1'b1,1'b0,8'hE0}] = {10'b0110001110,1'b1}; // D.0.7    rd+
    enc_rom[{1'b0,1'b0,8'hE1}] = {10'b0111010001,1'b0}; // D.1.7    rd-
    enc_rom[{1'b1,1'b0,8'hE1}] = {10'b1000101110,1'b1}; // D.1.7    rd+
    enc_rom[{1'b0,1'b0,8'hE2}] = {10'b1011010001,1'b0}; // D.2.7    rd-
    enc_rom[{1'b1,1'b0,8'hE2}] = {10'b0100101110,1'b1}; // D.2.7    rd+
    enc_rom[{1'b0,1'b0,8'hE3}] = {10'b1100011110,1'b1}; // D.3.7    rd-
    enc_rom[{1'b1,1'b0,8'hE3}] = {10'b1100010001,1'b0}; // D.3.7    rd+
    enc_rom[{1'b0,1'b0,8'hE4}] = {10'b1101010001,1'b0}; // D.4.7    rd-
    enc_rom[{1'b1,1'b0,8'hE4}] = {10'b0010101110,1'b1}; // D.4.7    rd+
    enc_rom[{1'b0,1'b0,8'hE5}] = {10'b1010011110,1'b1}; // D.5.7    rd-
    enc_rom[{1'b1,1'b0,8'hE5}] = {10'b1010010001,1'b0}; // D.5.7    rd+
    enc_rom[{1'b0,1'b0,8'hE6}] = {10'b0110011110,1'b1}; // D.6.7    rd-
    enc_rom[{1'b1,1'b0,8'hE6}] = {10'b0110010001,1'b0}; // D.6.7    rd+
    enc_rom[{1'b0,1'b0,8'hE7}] = {10'b1110001110,1'b1}; // D.7.7    rd-
    enc_rom[{1'b1,1'b0,8'hE7}] = {10'b0001110001,1'b0}; // D.7.7    rd+
    enc_rom[{1'b0,1'b0,8'hE8}] = {10'b1110010001,1'b0}; // D.8.7    rd-
    enc_rom[{1'b1,1'b0,8'hE8}] = {10'b0001101110,1'b1}; // D.8.7    rd+
    enc_rom[{1'b0,1'b0,8'hE9}] = {10'b1001011110,1'b1}; // D.9.7    rd-
    enc_rom[{1'b1,1'b0,8'hE9}] = {10'b1001010001,1'b0}; // D.9.7    rd+
    enc_rom[{1'b0,1'b0,8'hEA}] = {10'b0101011110,1'b1}; // D.10.7   rd-
    enc_rom[{1'b1,1'b0,8'hEA}] = {10'b0101010001,1'b0}; // D.10.7   rd+
    enc_rom[{1'b0,1'b0,8'hEB}] = {10'b1101001110,1'b1}; // D.11.7   rd-
    enc_rom[{1'b1,1'b0,8'hEB}] = {10'b1101001000,1'b0}; // D.11.7   rd+
    enc_rom[{1'b0,1'b0,8'hEC}] = {10'b0011011110,1'b1}; // D.12.7   rd-
    enc_rom[{1'b1,1'b0,8'hEC}] = {10'b0011010001,1'b0}; // D.12.7   rd+
    enc_rom[{1'b0,1'b0,8'hED}] = {10'b1011001110,1'b1}; // D.13.7   rd-
    enc_rom[{1'b1,1'b0,8'hED}] = {10'b1011001000,1'b0}; // D.13.7   rd+
    enc_rom[{1'b0,1'b0,8'hEE}] = {10'b0111001110,1'b1}; // D.14.7   rd-
    enc_rom[{1'b1,1'b0,8'hEE}] = {10'b0111001000,1'b0}; // D.14.7   rd+
    enc_rom[{1'b0,1'b0,8'hEF}] = {10'b0101110001,1'b0}; // D.15.7   rd-
    enc_rom[{1'b1,1'b0,8'hEF}] = {10'b1010001110,1'b1}; // D.15.7   rd+
    enc_rom[{1'b0,1'b0,8'hF0}] = {10'b0110110001,1'b0}; // D.16.7   rd-
    enc_rom[{1'b1,1'b0,8'hF0}] = {10'b1001001110,1'b1}; // D.16.7   rd+
    enc_rom[{1'b0,1'b0,8'hF1}] = {10'b1000110111,1'b1}; // D.17.7   rd-
    enc_rom[{1'b1,1'b0,8'hF1}] = {10'b1000110001,1'b0}; // D.17.7   rd+
    enc_rom[{1'b0,1'b0,8'hF2}] = {10'b0100110111,1'b1}; // D.18.7   rd-
    enc_rom[{1'b1,1'b0,8'hF2}] = {10'b0100110001,1'b0}; // D.18.7   rd+
    enc_rom[{1'b0,1'b0,8'hF3}] = {10'b1100101110,1'b1}; // D.19.7   rd-
    enc_rom[{1'b1,1'b0,8'hF3}] = {10'b1100100001,1'b0}; // D.19.7   rd+
    enc_rom[{1'b0,1'b0,8'hF4}] = {10'b0010110111,1'b1}; // D.20.7   rd-
    enc_rom[{1'b1,1'b0,8'hF4}] = {10'b0010110001,1'b0}; // D.20.7   rd+
    enc_rom[{1'b0,1'b0,8'hF5}] = {10'b1010101110,1'b1}; // D.21.7   rd-
    enc_rom[{1'b1,1'b0,8'hF5}] = {10'b1010100001,1'b0}; // D.21.7   rd+
    enc_rom[{1'b0,1'b0,8'hF6}] = {10'b0110101110,1'b1}; // D.22.7   rd-
    enc_rom[{1'b1,1'b0,8'hF6}] = {10'b0110100001,1'b0}; // D.22.7   rd+
    enc_rom[{1'b0,1'b0,8'hF7}] = {10'b1110100001,1'b0}; // D.23.7   rd-
    enc_rom[{1'b1,1'b0,8'hF7}] = {10'b0001011110,1'b1}; // D.23.7   rd+
    enc_rom[{1'b0,1'b0,8'hF8}] = {10'b1100110001,1'b0}; // D.24.7   rd-
    enc_rom[{1'b1,1'b0,8'hF8}] = {10'b0011001110,1'b1}; // D.24.7   rd+
    enc_rom[{1'b0,1'b0,8'hF9}] = {10'b1001101110,1'b1}; // D.25.7   rd-
    enc_rom[{1'b1,1'b0,8'hF9}] = {10'b1001100001,1'b0}; // D.25.7   rd+
    enc_rom[{1'b0,1'b0,8'hFA}] = {10'b0101101110,1'b1}; // D.26.7   rd-
    enc_rom[{1'b1,1'b0,8'hFA}] = {10'b0101100001,1'b0}; // D.26.7   rd+
    enc_rom[{1'b0,1'b0,8'hFB}] = {10'b1101100001,1'b0}; // D.27.7   rd-
    enc_rom[{1'b1,1'b0,8'hFB}] = {10'b0010011110,1'b1}; // D.27.7   rd+
    enc_rom[{1'b0,1'b0,8'hFC}] = {10'b0011101110,1'b1}; // D.28.7   rd-
    enc_rom[{1'b1,1'b0,8'hFC}] = {10'b0011100001,1'b0}; // D.28.7   rd+
    enc_rom[{1'b0,1'b0,8'hFD}] = {10'b1011100001,1'b0}; // D.29.7   rd-
    enc_rom[{1'b1,1'b0,8'hFD}] = {10'b0100011110,1'b1}; // D.29.7   rd+
    enc_rom[{1'b0,1'b0,8'hFE}] = {10'b0111100001,1'b0}; // D.30.7   rd-
    enc_rom[{1'b1,1'b0,8'hFE}] = {10'b1000011110,1'b1}; // D.30.7   rd+
    enc_rom[{1'b0,1'b0,8'hFF}] = {10'b1010110001,1'b0}; // D.31.7   rd-
    enc_rom[{1'b1,1'b0,8'hFF}] = {10'b0101001110,1'b1}; // D.31.7   rd+
    enc_rom[{1'b0,1'b1,8'h1C}] = {10'b0011110100,1'b0}; // K.28.0   rd-
    enc_rom[{1'b1,1'b1,8'h1C}] = {10'b1100001011,1'b1}; // K.28.0   rd+
    enc_rom[{1'b0,1'b1,8'h3C}] = {10'b0011111001,1'b1}; // K.28.1   rd-
    enc_rom[{1'b1,1'b1,8'h3C}] = {10'b1100000110,1'b0}; // K.28.1   rd+
    enc_rom[{1'b0,1'b1,8'h5C}] = {10'b0011110101,1'b1}; // K.28.2   rd-
    enc_rom[{1'b1,1'b1,8'h5C}] = {10'b1100001010,1'b0}; // K.28.2   rd+
    enc_rom[{1'b0,1'b1,8'h7C}] = {10'b0011110011,1'b1}; // K.28.3   rd-
    enc_rom[{1'b1,1'b1,8'h7C}] = {10'b1100001100,1'b0}; // K.28.3   rd+
    enc_rom[{1'b0,1'b1,8'h9C}] = {10'b0011110010,1'b0}; // K.28.4   rd-
    enc_rom[{1'b1,1'b1,8'h9C}] = {10'b1100001101,1'b1}; // K.28.4   rd+
    enc_rom[{1'b0,1'b1,8'hBC}] = {10'b0011111010,1'b1}; // K.28.5   rd-
    enc_rom[{1'b1,1'b1,8'hBC}] = {10'b1100000101,1'b0}; // K.28.5   rd+
    enc_rom[{1'b0,1'b1,8'hDC}] = {10'b0011110110,1'b1}; // K.28.6   rd-
    enc_rom[{1'b1,1'b1,8'hDC}] = {10'b1100001001,1'b0}; // K.28.6   rd+
    enc_rom[{1'b0,1'b1,8'hF7}] = {10'b1110101000,1'b0}; // K.23.7   rd-
    enc_rom[{1'b1,1'b1,8'hF7}] = {10'b0001010111,1'b1}; // K.23.7   rd+
    enc_rom[{1'b0,1'b1,8'hFB}] = {10'b1101101000,1'b0}; // K.27.7   rd-
    enc_rom[{1'b1,1'b1,8'hFB}] = {10'b0010010111,1'b1}; // K.27.7   rd+
    enc_rom[{1'b0,1'b1,8'hFC}] = {10'b0011111000,1'b0}; // K.28.7   rd-
    enc_rom[{1'b1,1'b1,8'hFC}] = {10'b1100000111,1'b1}; // K.28.7   rd+
    enc_rom[{1'b0,1'b1,8'hFD}] = {10'b1011101000,1'b0}; // K.29.7   rd-
    enc_rom[{1'b1,1'b1,8'hFD}] = {10'b0100010111,1'b1}; // K.29.7   rd+
    enc_rom[{1'b0,1'b1,8'hFE}] = {10'b0111101000,1'b0}; // K.30.7   rd-
    enc_rom[{1'b1,1'b1,8'hFE}] = {10'b1000010111,1'b1}; // K.30.7   rd+

    // ---- Known-Answer Table (docs/codec_8b10b_kat.txt) ----
    kat_add("K.28.0   rd-", 8'h1C, 1'b1, 1'b0, 10'b0011110100, 1'b0);
    kat_add("K.28.0   rd+", 8'h1C, 1'b1, 1'b1, 10'b1100001011, 1'b1);
    kat_add("K.28.1   rd-", 8'h3C, 1'b1, 1'b0, 10'b0011111001, 1'b1);
    kat_add("K.28.1   rd+", 8'h3C, 1'b1, 1'b1, 10'b1100000110, 1'b0);
    kat_add("K.28.2   rd-", 8'h5C, 1'b1, 1'b0, 10'b0011110101, 1'b1);
    kat_add("K.28.2   rd+", 8'h5C, 1'b1, 1'b1, 10'b1100001010, 1'b0);
    kat_add("K.28.3   rd-", 8'h7C, 1'b1, 1'b0, 10'b0011110011, 1'b1);
    kat_add("K.28.3   rd+", 8'h7C, 1'b1, 1'b1, 10'b1100001100, 1'b0);
    kat_add("K.28.4   rd-", 8'h9C, 1'b1, 1'b0, 10'b0011110010, 1'b0);
    kat_add("K.28.4   rd+", 8'h9C, 1'b1, 1'b1, 10'b1100001101, 1'b1);
    kat_add("K.28.5   rd-", 8'hBC, 1'b1, 1'b0, 10'b0011111010, 1'b1);
    kat_add("K.28.5   rd+", 8'hBC, 1'b1, 1'b1, 10'b1100000101, 1'b0);
    kat_add("K.28.6   rd-", 8'hDC, 1'b1, 1'b0, 10'b0011110110, 1'b1);
    kat_add("K.28.6   rd+", 8'hDC, 1'b1, 1'b1, 10'b1100001001, 1'b0);
    kat_add("K.28.7   rd-", 8'hFC, 1'b1, 1'b0, 10'b0011111000, 1'b0);
    kat_add("K.28.7   rd+", 8'hFC, 1'b1, 1'b1, 10'b1100000111, 1'b1);
    kat_add("K.23.7   rd-", 8'hF7, 1'b1, 1'b0, 10'b1110101000, 1'b0);
    kat_add("K.23.7   rd+", 8'hF7, 1'b1, 1'b1, 10'b0001010111, 1'b1);
    kat_add("K.27.7   rd-", 8'hFB, 1'b1, 1'b0, 10'b1101101000, 1'b0);
    kat_add("K.27.7   rd+", 8'hFB, 1'b1, 1'b1, 10'b0010010111, 1'b1);
    kat_add("K.29.7   rd-", 8'hFD, 1'b1, 1'b0, 10'b1011101000, 1'b0);
    kat_add("K.29.7   rd+", 8'hFD, 1'b1, 1'b1, 10'b0100010111, 1'b1);
    kat_add("K.30.7   rd-", 8'hFE, 1'b1, 1'b0, 10'b0111101000, 1'b0);
    kat_add("K.30.7   rd+", 8'hFE, 1'b1, 1'b1, 10'b1000010111, 1'b1);
    kat_add("D.0.0    rd-", 8'h00, 1'b0, 1'b0, 10'b1001110100, 1'b0);
    kat_add("D.0.0    rd+", 8'h00, 1'b0, 1'b1, 10'b0110001011, 1'b1);
    kat_add("D.31.7   rd-", 8'hFF, 1'b0, 1'b0, 10'b1010110001, 1'b0);
    kat_add("D.31.7   rd+", 8'hFF, 1'b0, 1'b1, 10'b0101001110, 1'b1);
    kat_add("D.28.5   rd-", 8'hBC, 1'b0, 1'b0, 10'b0011101010, 1'b0);
    kat_add("D.28.5   rd+", 8'hBC, 1'b0, 1'b1, 10'b0011101010, 1'b1);
    kat_add("D.21.2   rd-", 8'h55, 1'b0, 1'b0, 10'b1010100101, 1'b0);
    kat_add("D.21.2   rd+", 8'h55, 1'b0, 1'b1, 10'b1010100101, 1'b1);
    kat_add("D.10.5   rd-", 8'hAA, 1'b0, 1'b0, 10'b0101011010, 1'b0);
    kat_add("D.10.5   rd+", 8'hAA, 1'b0, 1'b1, 10'b0101011010, 1'b1);
    kat_add("D.31.3   rd-", 8'h7F, 1'b0, 1'b0, 10'b1010110011, 1'b1);
    kat_add("D.31.3   rd+", 8'h7F, 1'b0, 1'b1, 10'b0101001100, 1'b0);
    kat_add("D.11.7   rd-", 8'hEB, 1'b0, 1'b0, 10'b1101001110, 1'b1);
    kat_add("D.11.7   rd+", 8'hEB, 1'b0, 1'b1, 10'b1101001000, 1'b0);
    kat_add("D.13.7   rd-", 8'hED, 1'b0, 1'b0, 10'b1011001110, 1'b1);
    kat_add("D.13.7   rd+", 8'hED, 1'b0, 1'b1, 10'b1011001000, 1'b0);
    kat_add("D.14.7   rd-", 8'hEE, 1'b0, 1'b0, 10'b0111001110, 1'b1);
    kat_add("D.14.7   rd+", 8'hEE, 1'b0, 1'b1, 10'b0111001000, 1'b0);
    kat_add("D.17.7   rd-", 8'hF1, 1'b0, 1'b0, 10'b1000110111, 1'b1);
    kat_add("D.17.7   rd+", 8'hF1, 1'b0, 1'b1, 10'b1000110001, 1'b0);
    kat_add("D.18.7   rd-", 8'hF2, 1'b0, 1'b0, 10'b0100110111, 1'b1);
    kat_add("D.18.7   rd+", 8'hF2, 1'b0, 1'b1, 10'b0100110001, 1'b0);
    kat_add("D.20.7   rd-", 8'hF4, 1'b0, 1'b0, 10'b0010110111, 1'b1);
    kat_add("D.20.7   rd+", 8'hF4, 1'b0, 1'b1, 10'b0010110001, 1'b0);
    // <<<GENERATED-TABLES-END>>>

    // ---- brute-force inversion, in three passes ----
    // 1. assume nothing is a codeword
    for (int rd = 0; rd < 2; rd++)
      for (int c = 0; c < 1024; c++)
        dec_tbl[{rd[0], c[9:0]}] =
            mk_rx(1'b1, 1'b0, 1'b0, 8'h00, rd_advance(c[9:0], rd[0]));

    // 2. words that are legal but carry the opposite polarity to the RD we are
    //    in.  Done before pass 3 so that a word which is simultaneously the
    //    correct variant here and the alternate variant of the same symbol
    //    (every balanced, non-alternating symbol) ends up marked clean.
    for (int rd = 0; rd < 2; rd++)
      for (int k = 0; k < 2; k++)
        for (int d = 0; d < 256; d++) begin
          if (!enc_ok[{k[0], d[7:0]}]) continue;
          cw = enc_rom[{~rd[0], k[0], d[7:0]}][10:1];
          dec_tbl[{rd[0], cw}] =
              mk_rx(1'b0, 1'b1, k[0], d[7:0], rd_advance(cw, rd[0]));
        end

    // 3. words that are exactly what the transmitter would have sent
    for (int rd = 0; rd < 2; rd++)
      for (int k = 0; k < 2; k++)
        for (int d = 0; d < 256; d++) begin
          if (!enc_ok[{k[0], d[7:0]}]) continue;
          cw = enc_rom[{rd[0], k[0], d[7:0]}][10:1];
          dec_tbl[{rd[0], cw}] =
              mk_rx(1'b0, 1'b0, k[0], d[7:0], rd_advance(cw, rd[0]));
        end
  endfunction

  // ---- encode ------------------------------------------------------------
  // kerr mirrors the DUT's specified contract for an unencodable control
  // request: nothing legal goes on the wire (the all-zero word is not a
  // codeword, so the far end reports a code error too) and RD is untouched.
  function automatic ref_tx_t ref_encode(input bit [7:0] data,
                                         input bit       k,
                                         input bit       rd);
    ref_tx_t  t;
    bit [10:0] e;
    ref_build();
    t.kerr = k && !enc_ok[{k, data}];
    if (t.kerr) begin
      t.code   = 10'b0;
      t.rd_out = rd;
    end else begin
      e        = enc_rom[{rd, k, data}];
      t.code   = e[10:1];
      t.rd_out = e[0];
    end
    return t;
  endfunction

  // ---- decode ------------------------------------------------------------
  function automatic ref_rx_t ref_decode(input bit [9:0] cw, input bit rd);
    ref_build();
    ref_decode = dec_tbl[{rd, cw}];
  endfunction

  // ---- one full pass through the link ------------------------------------
  // The caller threads the two running-disparity registers (the transmitter's
  // and the receiver's) so the model holds no hidden state and a scoreboard
  // can replay any stream from any point.
  function automatic ref_exp_t ref_link_step(input bit [7:0] data,
                                             input bit       k,
                                             input bit [9:0] err_mask,
                                             input bit       tx_rd,
                                             input bit       rx_rd);
    bit [9:0] wc;
    ref_tx_t  tx;
    ref_rx_t  rx;
    ref_exp_t e;
    tx = ref_encode(data, k, tx_rd);
    wc = tx.code ^ err_mask;
    rx = ref_decode(wc, rx_rd);
    e.enc_code     = tx.code;
    e.wire_code    = wc;
    e.enc_kerr     = tx.kerr;
    e.enc_comma    = ref_is_comma(tx.code);
    e.enc_rd       = tx.rd_out;
    e.out_data     = rx.data;
    e.out_k        = rx.k;
    e.out_code_err = rx.code_err;
    e.out_disp_err = rx.disp_err;
    e.out_comma    = ref_is_comma(wc);
    e.out_rd       = rx.rd_out;
    return e;
  endfunction

  // ---- what checks the checker -------------------------------------------
  // Replays the committed Known-Answer Table through the model's own encode
  // and decode paths before any DUT result is judged.  Returns the number of
  // mismatches; 0 means the model agrees with the table that docs/gen_kat.py
  // proved.
  function automatic int kat_selfcheck(input bit verbose = 1'b0);
    ref_tx_t  tx;
    ref_rx_t  rx;
    int       bad = 0;
    ref_build();
    for (int i = 0; i < kat_n; i++) begin
      tx = ref_encode(kat_data[i], kat_k[i], kat_rd[i]);
      if (tx.kerr || tx.code !== kat_code[i] || tx.rd_out !== kat_rdo[i]) begin
        bad++;
        $display("  KAT encode MISMATCH %s: got %b rd%0d kerr=%0b, want %b rd%0d",
                 kat_name[i], tx.code, tx.rd_out, tx.kerr, kat_code[i],
                 kat_rdo[i]);
      end
      // and straight back again
      rx = ref_decode(kat_code[i], kat_rd[i]);
      if (rx.code_err || rx.disp_err || rx.data !== kat_data[i] ||
          rx.k !== kat_k[i] || rx.rd_out !== kat_rdo[i]) begin
        bad++;
        $display("  KAT decode MISMATCH %s: got %02h k=%0b ce=%0b de=%0b rd%0d",
                 kat_name[i], rx.data, rx.k, rx.code_err, rx.disp_err,
                 rx.rd_out);
      end
    end
    if (verbose)
      $display("  KAT self-check: %0d vectors, %0d mismatch(es)", kat_n, bad);
    return bad;
  endfunction

  // ---- an independent restatement of the code's defining properties ------
  // Cheap enough to run at the start of every simulation, and it means the
  // committed tables are re-proved inside the simulator rather than only in
  // Python.  Returns the number of violations.
  function automatic int property_selfcheck(input bit verbose = 1'b0);
    int bad = 0, n1, cnt, run, worst = 0;
    bit [9:0] cw;
    bit rd_out;
    ref_build();
    for (int rd = 0; rd < 2; rd++)
      for (int k = 0; k < 2; k++)
        for (int d = 0; d < 256; d++) begin
          if (!enc_ok[{k[0], d[7:0]}]) continue;
          cw     = enc_rom[{rd[0], k[0], d[7:0]}][10:1];
          rd_out = enc_rom[{rd[0], k[0], d[7:0]}][0];
          // P1 - DC balance
          n1 = $countones(cw);
          if (n1 < 4 || n1 > 6) begin
            bad++;
            $display("  P1 VIOLATION: %s%0d.%0d rd%0d -> %b has %0d ones",
                     k[0] ? "K" : "D", d[4:0], d[7:5], rd, cw, n1);
          end
          // P2 - RD' must be what the received bits imply
          if (rd_out !== rd_advance(cw, rd[0])) begin
            bad++;
            $display("  P2 VIOLATION: %s%0d.%0d rd%0d -> %b claims rd%0d",
                     k[0] ? "K" : "D", d[4:0], d[7:5], rd, cw, rd_out);
          end
          // P3 - no run of 6 inside a codeword
          run = 1;
          for (int b = 8; b >= 0; b--) begin
            run = (cw[b] === cw[b+1]) ? run + 1 : 1;
            if (run > worst) worst = run;
          end
          // P5 - the comma belongs to K.28.1/.5/.7 alone
          if (ref_is_comma(cw) && !(k[0] && d[4:0] == 5'd28 &&
              (d[7:5] == 3'd1 || d[7:5] == 3'd5 || d[7:5] == 3'd7))) begin
            bad++;
            $display("  P5 VIOLATION: %s%0d.%0d rd%0d -> %b carries a comma",
                     k[0] ? "K" : "D", d[4:0], d[7:5], rd, cw);
          end
        end
    if (worst > 5) begin
      bad++;
      $display("  P3 VIOLATION: a codeword contains a run of %0d", worst);
    end
    // P4 - unique decodability: every codeword must invert to its own symbol
    cnt = 0;
    for (int rd = 0; rd < 2; rd++)
      for (int k = 0; k < 2; k++)
        for (int d = 0; d < 256; d++) begin
          ref_rx_t rx;
          if (!enc_ok[{k[0], d[7:0]}]) continue;
          cnt++;
          cw = enc_rom[{rd[0], k[0], d[7:0]}][10:1];
          rx = dec_tbl[{rd[0], cw}];
          if (rx.code_err || rx.disp_err || rx.data !== d[7:0] ||
              rx.k !== k[0]) begin
            bad++;
            $display("  P4 VIOLATION: %s%0d.%0d rd%0d -> %b decodes to %02h k=%0b",
                     k[0] ? "K" : "D", d[4:0], d[7:5], rd, cw, rx.data, rx.k);
          end
        end
    if (verbose)
      $display("  property self-check: %0d symbol/RD pairs, longest run %0d, %0d violation(s)",
               cnt, worst, bad);
    return bad;
  endfunction

endpackage : codec_8b10b_ref_pkg
