#!/usr/bin/env python3
"""
Day29 - 8b/10b line-code table generator, exhaustive property validator and
Known-Answer-Table emitter.

WHY THIS SCRIPT EXISTS
----------------------
8b/10b is a *table* code.  Anybody can transcribe the 5b/6b and 3b/4b tables
from a standard, but a single flipped bit in a 40-row table produces RTL that
looks correct, passes a round-trip test (encoder and decoder agree because they
share the typo) and still violates the line code on the wire.  So the tables
are not trusted here - they are *proved* against the five defining properties
of the code, exhaustively, over every symbol in both running-disparity states:

  P1  every 10-bit codeword has 4, 5 or 6 ones                (DC balance)
  P2  running disparity stays in {-1,+1} at every sub-block   (bounded RD)
  P3  no run of more than 5 identical bits, including across
      every legal codeword-to-codeword junction               (clock recovery)
  P4  the 10-bit -> 8-bit map is a function: no codeword ever
      decodes to two different symbols                        (decodability)
  P5  the comma sequence 0011111 / 1100000 appears *only*
      inside K.28.1 / K.28.5 / K.28.7 and never straddles a
      junction of any two legal non-comma codewords           (unique comma)

plus the three landmark codewords everyone knows by heart:

      K.28.5 = 0011111010 / 1100000101
      K.28.1 = 0011111001 / 1100000110
      K.28.7 = 0011111000 / 1100000111

P3 and P5 are junction properties: they are checked over all 536 x 536 ordered
pairs of legal codewords that can actually follow one another (RD-compatible),
which is what makes them meaningful rather than decorative.

The script then emits:
  * docs/codec_8b10b_kat.txt      - human-readable Known-Answer Table
  * the SystemVerilog body of the flat 1024-entry encode ROM used by the
    *golden reference model* (codec_8b10b_ref_pkg.sv)

Note the deliberate asymmetry that gives the verification its independence:
the DUT (codec_8b10b.sv) implements the code the way hardware does - two small
sub-block tables plus the disparity / alternate-D.x.A7 *rules* - while the
reference model is a flat, fully-expanded {RD, K, byte} -> {codeword, RD'} ROM
generated by this script.  A rule bug in the DUT cannot hide in the model,
because the model has no rules.

Usage:  python3 docs/gen_kat.py            # validate + write KAT + print SV
"""

import os
import random
import sys

# ---------------------------------------------------------------------------
# The two sub-block tables.  Both are given as the RD- ("negative running
# disparity") column; the RD+ column is derived by the rules below.
# Bit order is transmit order: 6b = abcdei (a first), 4b = fghj (f first).
# ---------------------------------------------------------------------------

# 5b/6b, indexed by x = data[4:0].  D.x -> abcdei at RD-.
D5B6B_RDNEG = [
    0b100111,  # D.00
    0b011101,  # D.01
    0b101101,  # D.02
    0b110001,  # D.03  balanced
    0b110101,  # D.04
    0b101001,  # D.05  balanced
    0b011001,  # D.06  balanced
    0b111000,  # D.07  balanced BUT alternating (see BALANCED_ALTERNATING_5B6B)
    0b111001,  # D.08
    0b100101,  # D.09  balanced
    0b010101,  # D.10  balanced
    0b110100,  # D.11  balanced
    0b001101,  # D.12  balanced
    0b101100,  # D.13  balanced
    0b011100,  # D.14  balanced
    0b010111,  # D.15
    0b011011,  # D.16
    0b100011,  # D.17  balanced
    0b010011,  # D.18  balanced
    0b110010,  # D.19  balanced
    0b001011,  # D.20  balanced
    0b101010,  # D.21  balanced
    0b011010,  # D.22  balanced
    0b111010,  # D.23
    0b110011,  # D.24
    0b100110,  # D.25  balanced
    0b010110,  # D.26  balanced
    0b110110,  # D.27
    0b001110,  # D.28  balanced
    0b101110,  # D.29
    0b011110,  # D.30
    0b101011,  # D.31
]

# 5b/6b for the control (K) symbols.  Only K.23/27/28/29/30 exist; the ones
# that are not K.28 reuse the D 6b sub-block of the same x.
K5B6B_RDNEG = dict(D5B6B_RDNEG_ITEMS := {})  # placeholder, filled below
K5B6B_RDNEG = {
    23: D5B6B_RDNEG[23],
    27: D5B6B_RDNEG[27],
    28: 0b001111,  # the only K-exclusive 6b sub-block - the comma carrier
    29: D5B6B_RDNEG[29],
    30: D5B6B_RDNEG[30],
}

# 3b/4b, indexed by y = data[7:5].  D.x.y -> fghj at RD-.
D3B4B_RDNEG = [
    0b1011,  # D.x.0
    0b1001,  # D.x.1  balanced
    0b0101,  # D.x.2  balanced
    0b1100,  # D.x.3  balanced
    0b1101,  # D.x.4
    0b1010,  # D.x.5  balanced
    0b0110,  # D.x.6  balanced
    0b1110,  # D.x.7  "primary"  P7
]
D3B4B_A7_RDNEG = 0b0111  # the alternate D.x.A7 encoding

# 3b/4b for control symbols, RD- column.  Differs from the D column exactly
# where the D entry is balanced but the code still has to alternate (y in
# 1,2,5,6) and at y=7, where K always takes the A7 pattern.
K3B4B_RDNEG = [
    0b1011,  # K.x.0   (same as D)
    0b0110,  # K.x.1   (complement of D.x.1)
    0b1010,  # K.x.2   (complement of D.x.2)
    0b1100,  # K.x.3   (same as D)
    0b1101,  # K.x.4   (same as D)
    0b0101,  # K.x.5   (complement of D.x.5)
    0b1001,  # K.x.6   (complement of D.x.6)
    0b0111,  # K.x.7   (= A7)
]

# The twelve legal control symbols, as (x, y).
K_SYMBOLS = [(28, y) for y in range(8)] + [(23, 7), (27, 7), (29, 7), (30, 7)]

# The two "balanced but still alternating" data entries.  Every other balanced
# sub-block transmits the same bits in both RD states; these two do not,
# because reusing one pattern in both states would let a 6-bit run form at a
# codeword junction.  They are the classic place to get the table wrong, and
# the P3 junction check below is what catches it.
BALANCED_ALTERNATING_5B6B = {7}    # D.07 = 000111 / 111000
BALANCED_ALTERNATING_3B4B = {3}    # D.x.3 = 1100   / 0011

# K.28.7 is the one legal symbol the standard restricts: it is the only comma
# code whose trailing bits can form a 6-bit run with the *next* codeword, so it
# may not be used adjacent to arbitrary traffic.  The junction sweep confirms
# this rather than assuming it, and reports the exact offending successor set.
K28_7 = ((7 << 5) | 28, 1)

# D.x.A7 replaces D.x.P7 when the RD *entering the 3b/4b sub-block* is
# negative and x in {17,18,20}, or positive and x in {11,13,14}.  This is the
# one rule in the whole code that exists purely to keep run length <= 5.
A7_WHEN_RD_NEG = {17, 18, 20}
A7_WHEN_RD_POS = {11, 13, 14}

RD_NEG, RD_POS = 0, 1  # RD- == 0, RD+ == 1 (matches the RTL encoding)


# ---------------------------------------------------------------------------
# Encoder (the generator's own model - the source of truth for the ROM)
# ---------------------------------------------------------------------------

def ones(v, w):
    return bin(v & ((1 << w) - 1)).count("1")


def disp(v, w):
    """Disparity of a w-bit sub-block: (#ones - #zeros)."""
    return 2 * ones(v, w) - w


def sub_encode(code_rdneg, w, rd, alternate=False):
    """Pick the RD- or RD+ variant of a sub-block and return (code, rd_out).

    An unbalanced sub-block always uses the variant whose disparity opposes the
    current RD (the RD+ variant is the bit complement), and flips RD.  A
    balanced sub-block leaves RD alone; it normally transmits the same bits in
    both states, unless it is one of the alternating entries (D.07, D.x.3 and
    every control sub-block), which swap to the complement at RD+ without
    changing RD.
    """
    d = disp(code_rdneg, w)
    mask = (1 << w) - 1
    if d == 0 and not alternate:
        return code_rdneg, rd
    code = code_rdneg if rd == RD_NEG else (~code_rdneg) & mask
    if d == 0:
        return code, rd  # balanced but alternating: RD unchanged
    return code, (RD_POS if rd == RD_NEG else RD_NEG)


def encode(byte, k, rd):
    """Encode one symbol.  Returns (codeword10, rd_out) or (None, rd) if the
    requested control symbol does not exist."""
    x, y = byte & 0x1F, (byte >> 5) & 0x7
    if k:
        if (x, y) not in K_SYMBOLS:
            return None, rd
        c6, rd1 = sub_encode(K5B6B_RDNEG[x], 6, rd, alternate=True)
        c4, rd2 = sub_encode(K3B4B_RDNEG[y], 4, rd1, alternate=True)
    else:
        c6, rd1 = sub_encode(D5B6B_RDNEG[x], 6, rd,
                             alternate=x in BALANCED_ALTERNATING_5B6B)
        use_a7 = y == 7 and (
            (rd1 == RD_NEG and x in A7_WHEN_RD_NEG)
            or (rd1 == RD_POS and x in A7_WHEN_RD_POS)
        )
        c4, rd2 = sub_encode(D3B4B_A7_RDNEG if use_a7 else D3B4B_RDNEG[y], 4,
                             rd1, alternate=y in BALANCED_ALTERNATING_3B4B)
    return (c6 << 4) | c4, rd2


def bits(v, w):
    return format(v, "0%db" % w)


def sym_name(byte, k):
    return "%s.%d.%d" % ("K" if k else "D", byte & 0x1F, (byte >> 5) & 0x7)


# ---------------------------------------------------------------------------
# Build the complete code: every symbol in both RD states
# ---------------------------------------------------------------------------

def build():
    """Return (table, cw_map).

    table[(byte, k, rd)]  = (codeword, rd_out)
    cw_map[codeword]      = (byte, k)          # the decode direction
    """
    table, cw_map = {}, {}
    symbols = [(b, 0) for b in range(256)] + [
        ((y << 5) | x, 1) for (x, y) in K_SYMBOLS
    ]
    for byte, k in symbols:
        for rd in (RD_NEG, RD_POS):
            cw, rd_out = encode(byte, k, rd)
            assert cw is not None, "legal symbol failed to encode"
            table[(byte, k, rd)] = (cw, rd_out)
            prev = cw_map.get(cw)
            if prev is not None and prev != (byte, k):
                raise AssertionError(
                    "P4 VIOLATION: codeword %s decodes to both %s and %s"
                    % (bits(cw, 10), sym_name(*prev), sym_name(byte, k))
                )
            cw_map[cw] = (byte, k)
    return table, cw_map


# ---------------------------------------------------------------------------
# The five properties
# ---------------------------------------------------------------------------

def max_run(s):
    best = run = 1
    for i in range(1, len(s)):
        run = run + 1 if s[i] == s[i - 1] else 1
        best = max(best, run)
    return best


COMMA = ("0011111", "1100000")


def check_properties(table, cw_map):
    fails = []

    def fail(msg):
        fails.append(msg)

    # ---- P1 DC balance, and P2 bounded / consistent running disparity ----
    for (byte, k, rd), (cw, rd_out) in sorted(table.items()):
        n1 = ones(cw, 10)
        if n1 not in (4, 5, 6):
            fail("P1: %s rd%s -> %s has %d ones"
                 % (sym_name(byte, k), "-+"[rd], bits(cw, 10), n1))
        # RD' must equal RD advanced by the codeword's own disparity, and the
        # intermediate sub-block RD must also stay in range.
        d6, d4 = disp(cw >> 4, 6), disp(cw & 0xF, 4)
        rd_mid = rd if d6 == 0 else (RD_POS if d6 > 0 else RD_NEG)
        exp_out = rd_mid if d4 == 0 else (RD_POS if d4 > 0 else RD_NEG)
        if exp_out != rd_out:
            fail("P2: %s rd%s -> %s ends rd%s, disparity says rd%s"
                 % (sym_name(byte, k), "-+"[rd], bits(cw, 10),
                    "-+"[rd_out], "-+"[exp_out]))
        # A sub-block must never push RD the way it already points.
        if (rd == RD_NEG and d6 < 0) or (rd == RD_POS and d6 > 0):
            fail("P2: %s rd%s 6b sub-block %s worsens disparity"
                 % (sym_name(byte, k), "-+"[rd], bits(cw >> 4, 6)))
        if (rd_mid == RD_NEG and d4 < 0) or (rd_mid == RD_POS and d4 > 0):
            fail("P2: %s rd%s 4b sub-block %s worsens disparity"
                 % (sym_name(byte, k), "-+"[rd], bits(cw & 0xF, 4)))

    # ---- P3 / P5 junction properties ----
    # Group codewords by (rd_in, rd_out) so only sequences that can really
    # occur on the wire are examined.
    by_rd_in = {RD_NEG: [], RD_POS: []}
    for (byte, k, rd), (cw, rd_out) in table.items():
        by_rd_in[rd].append((cw, rd_out, byte, k))
    for lst in by_rd_in.values():
        lst.sort()

    k287_bad = []  # successors that K.28.7 may not be followed by

    for rd_in in (RD_NEG, RD_POS):
        for cw, rd_out, byte, k in by_rd_in[rd_in]:
            s = bits(cw, 10)
            if max_run(s) > 5:
                fail("P3: %s rd%s -> %s has a run of %d"
                     % (sym_name(byte, k), "-+"[rd_in], s, max_run(s)))
            # A comma may appear only in K.28.1/.5/.7, and only aligned to the
            # start of the codeword - that is what makes it a framing marker.
            hits = [i for i in range(len(s) - 6)
                    if s[i:i + 7] in COMMA]
            is_comma = bool(hits)
            if is_comma:
                if (byte & 0x1F, (byte >> 5) & 0x7) not in ((28, 1), (28, 5),
                                                            (28, 7)):
                    fail("P5: non-comma symbol %s rd%s -> %s contains a comma"
                         % (sym_name(byte, k), "-+"[rd_in], s))
                elif hits != [0]:
                    fail("P5: %s rd%s -> %s carries a misaligned comma at %s"
                         % (sym_name(byte, k), "-+"[rd_in], s, hits))

            for cw2, _, byte2, k2 in by_rd_in[rd_out]:
                j = s + bits(cw2, 10)
                bad = None
                if max_run(j) > 5:
                    bad = "run of %d" % max_run(j)
                # Only windows that actually straddle the boundary (start at
                # offset 4..9) can *manufacture* a comma; a comma at offset 10
                # is just the second codeword's own aligned comma.
                elif any(j[i:i + 7] in COMMA for i in range(4, 10)):
                    bad = "manufactured comma"
                if bad is None:
                    continue
                if (byte, k) == K28_7:
                    k287_bad.append((sym_name(byte2, k2), j, bad))
                else:
                    fail("P3/P5: junction %s|%s = %s : %s"
                         % (sym_name(byte, k), sym_name(byte2, k2), j, bad))

    # ---- landmarks ----
    landmarks = {
        ((5 << 5) | 28, 1): (0b0011111010, 0b1100000101),  # K.28.5
        ((1 << 5) | 28, 1): (0b0011111001, 0b1100000110),  # K.28.1
        ((7 << 5) | 28, 1): (0b0011111000, 0b1100000111),  # K.28.7
    }
    for (byte, k), (want_neg, want_pos) in landmarks.items():
        got_neg = table[(byte, k, RD_NEG)][0]
        got_pos = table[(byte, k, RD_POS)][0]
        if (got_neg, got_pos) != (want_neg, want_pos):
            fail("LANDMARK: %s = %s/%s, expected %s/%s"
                 % (sym_name(byte, k), bits(got_neg, 10), bits(got_pos, 10),
                    bits(want_neg, 10), bits(want_pos, 10)))

    # ---- P4 already enforced during build(); restate it as a count ----
    if len(set(cw_map.values())) != 268:
        fail("P4: codewords cover %d symbols, expected 268 (256 D + 12 K)"
             % len(set(cw_map.values())))

    return fails, k287_bad


def check_stream(table, n=200000, seed=29):
    """Random-stream sanity: encode a long random symbol stream and confirm no
    run exceeds 5 and the cumulative imbalance stays tiny.  K.28.7 is left out
    for the reason the junction sweep proves: the standard restricts it."""
    rng = random.Random(seed)
    syms = [(b, 0) for b in range(256)] + [
        ((y << 5) | x, 1) for (x, y) in K_SYMBOLS if (x, y) != (28, 7)
    ]
    rd, wire = RD_NEG, []
    for _ in range(n):
        byte, k = rng.choice(syms)
        cw, rd = table[(byte, k, rd)]
        wire.append(bits(cw, 10))
    s = "".join(wire)
    return max_run(s), s.count("1") - s.count("0")


# ---------------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------------

HERE = os.path.dirname(os.path.abspath(__file__))

# The symbols that go into the committed Known-Answer Table: every control
# code, the classic data landmarks, and the six A7 symbols (the only place the
# alternate-encoding rule can be got wrong).
KAT_SYMBOLS = (
    [((y << 5) | x, 1) for (x, y) in K_SYMBOLS]
    + [(0x00, 0), (0xFF, 0), (0xBC, 0), (0x55, 0), (0xAA, 0), (0x7F, 0)]
    + [((7 << 5) | x, 0) for x in (11, 13, 14, 17, 18, 20)]
)


def write_kat(table):
    path = os.path.join(HERE, "codec_8b10b_kat.txt")
    with open(path, "w") as f:
        f.write("8b/10b Known-Answer Table\n")
        f.write("Generated by gen_kat.py after the exhaustive property "
                "check below passed.\n")
        f.write("Codewords are shown in transmit order abcdei fghj "
                "(leftmost bit on the wire first).\n\n")
        f.write("%-8s %-4s %-6s   %-13s %-4s   %-13s %-4s\n"
                % ("symbol", "byte", "K", "RD- codeword", "RD'", "RD+ codeword",
                   "RD'"))
        f.write("-" * 74 + "\n")
        for byte, k in KAT_SYMBOLS:
            cn, rn = table[(byte, k, RD_NEG)]
            cp, rp = table[(byte, k, RD_POS)]
            f.write("%-8s 0x%02X %-6d   %s %s   %-4s %s %s   %-4s\n"
                    % (sym_name(byte, k), byte, k,
                       bits(cn >> 4, 6), bits(cn & 0xF, 4), "-+"[rn],
                       bits(cp >> 4, 6), bits(cp & 0xF, 4), "-+"[rp]))
    return path


BEGIN_MARK = "    // <<<GENERATED-TABLES-BEGIN>>>"
END_MARK = "    // <<<GENERATED-TABLES-END>>>"


def sv_tables(table):
    """Emit the flat tables spliced into codec_8b10b_ref_pkg.sv.

    Three blocks, all pure data - no rules, which is the whole point of the
    reference model:
      enc_ok  [{k, byte}]        - does this symbol exist at all
      enc_rom [{rd, k, byte}]    - {codeword[9:0], rd_out}
      kat_add(...)               - the committed Known-Answer Table
    """
    out = [
        "    // ---- generated by docs/gen_kat.py; run `make kat` to refresh ----",
        "    // Every legal symbol, fully expanded.  No encode rule is applied",
        "    // anywhere in this package - if the DUT's rules are wrong, these",
        "    // numbers are what say so.",
        "",
        "    for (int d = 0; d < 256; d++) enc_ok[{1'b0, d[7:0]}] = 1'b1;",
    ]
    for x, y in K_SYMBOLS:
        b = (y << 5) | x
        out.append("    enc_ok[{1'b1,8'h%02X}] = 1'b1; // %s" % (b, sym_name(b, 1)))
    out.append("")
    for k in (0, 1):
        for byte in range(256):
            if k and (byte & 0x1F, (byte >> 5) & 0x7) not in K_SYMBOLS:
                continue
            for rd in (RD_NEG, RD_POS):
                cw, rd_out = table[(byte, k, rd)]
                out.append(
                    "    enc_rom[{1'b%d,1'b%d,8'h%02X}] = {10'b%s,1'b%d}; // %-8s rd%s"
                    % (rd, k, byte, bits(cw, 10), rd_out, sym_name(byte, k),
                       "-+"[rd])
                )
    out.append("")
    out.append("    // ---- Known-Answer Table (docs/codec_8b10b_kat.txt) ----")
    for byte, k in KAT_SYMBOLS:
        for rd in (RD_NEG, RD_POS):
            cw, rd_out = table[(byte, k, rd)]
            out.append(
                '    kat_add("%-8s rd%s", 8\'h%02X, 1\'b%d, 1\'b%d, '
                "10'b%s, 1'b%d);"
                % (sym_name(byte, k), "-+"[rd], byte, k, rd, bits(cw, 10),
                   rd_out)
            )
    return "\n".join(out)


def splice_ref(table):
    """Rewrite the generated region of codec_8b10b_ref_pkg.sv in place."""
    path = os.path.join(os.path.dirname(HERE), "codec_8b10b_ref_pkg.sv")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        src = f.read()
    if BEGIN_MARK not in src or END_MARK not in src:
        raise SystemExit("markers missing in %s" % path)
    head = src.split(BEGIN_MARK)[0]
    tail = src.split(END_MARK)[1]
    with open(path, "w") as f:
        f.write(head + BEGIN_MARK + "\n" + sv_tables(table) + "\n" + END_MARK
                + tail)
    return path


def main():
    table, cw_map = build()
    fails, k287_bad = check_properties(table, cw_map)
    worst_run, bal = check_stream(table)
    if worst_run > 5:
        fails.append("P3: random 200k-symbol stream has a run of %d" % worst_run)

    njunc = sum(1 for _ in table) * 268  # ordered RD-compatible pairs, approx
    print("8b/10b table validation")
    print("  symbols ............... %d (256 D + 12 K), each in 2 RD states"
          % (len(table) // 2))
    print("  distinct codewords .... %d" % len(cw_map))
    print("  worst run, 200k-symbol random stream ... %d bits" % worst_run)
    print("  running imbalance, same stream ......... %+d bits" % bal)
    if fails:
        print("\n%d PROPERTY VIOLATION(S):" % len(fails))
        for m in fails[:40]:
            print("   " + m)
        if len(fails) > 40:
            print("   ... and %d more" % (len(fails) - 40))
        return 1
    print("  P1 DC balance .......... PASS (all codewords have 4/5/6 ones)")
    print("  P2 bounded disparity ... PASS (RD in {-1,+1} at every sub-block)")
    print("  P3 run length <= 5 ..... PASS (~%d legal codeword junctions)"
          % njunc)
    print("  P4 unique decode ....... PASS (%d codewords, onto 268 symbols)"
          % len(cw_map))
    print("  P5 unique comma ........ PASS (aligned, only in K.28.1/.5/.7, "
          "never manufactured at a junction)")
    print("  landmarks K.28.1/.5/.7 . PASS")

    # K.28.7 is legal but restricted; report exactly how, rather than assuming.
    succ = sorted({n for n, _, _ in k287_bad})
    print("\n  K.28.7 restriction (derived, not assumed):")
    print("    %d successor codewords would break run<=5 or forge a comma"
          % len(k287_bad))
    print("    offending successors: %s" % ", ".join(succ))
    print("    => the testbench must not place K.28.7 next to these; the "
          "code\n       itself is sound for the other %d symbols."
          % (268 - len(succ)))

    path = write_kat(table)
    print("\nwrote %s" % path)
    ref = splice_ref(table)
    if ref:
        print("spliced generated tables into %s" % ref)
    else:
        print("codec_8b10b_ref_pkg.sv not found - nothing to splice")
    return 0


if __name__ == "__main__":
    sys.exit(main())
